---
# Install some AE-DIR script tools and documentation files

- name: "Create directory structure {{ aedir_prefix }}"
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
  with_items:
    - "{{ aedir_prefix }}"
    - "{{ aedir_etc }}"
    - "{{ aedir_bin }}"
    - "{{ aedir_sbin }}"
    - "{{ aedir_rundir }}"

- name: "Create client config file {{ aedir_etc }}/ldap.conf from template"
  template:
    src: "ldap.conf.j2"
    dest: "{{ aedir_etc }}/ldap.conf"
    owner: root
    group: root
    mode: 0644
  notify:
  - restart slapd

- name: "Create logging config file {{ aedir_etc }}/ae-logging.conf from template"
  template:
    src: "ae-logging.conf.j2"
    dest: "{{ aedir_etc }}/ae-logging.conf"
    owner: root
    group: root
    mode: 0644

- name: "install CA cert for SMTP/STARTTLS"
  copy:
    src: "{{ smtp_cacert_filename }}"
    dest: "{{ smtp_cacert_pathname }}"
    follow: no
    owner: root
    group: root
    mode: u=rw,g=r,o=r
    directory_mode: u=rwx,g=rx,o=rx
