---

- name: "Install C compiler packages on {{ lsb_id }}"
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - gcc
    - openssl-devel
    - cyrus-sasl-devel
    - openldap-devel
    - python-devel
    - libffi-devel
  when: aedir_pip_needs_compiler==True

- name: "Install base packages on {{ lsb_id }}"
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - python-setuptools
    - python-virtualenv
    - python-pip
    - python-cffi
  notify:
    - restart aedirpwd
    - restart hotp_validator
    - restart oathenroll
    - restart bind_proxy
    - restart web2ldap

- name: "AE-DIR tools installation in virtualenv {{ aedir_prefix }}"
  include_tasks: "aedir_tools_venv.yml"
