---

- name: "Install base packages on {{ ansible_lsb.id }}"
  apt:
    name: "{{ item }}"
    state: installed
    update_cache: no
    install_recommends: no
    dpkg_options: 'force-confold,force-confdef'
  with_items:
    - cron
    - python
    - python-paramiko
    - python-webpy
    - tar
    - gzip
    - gcc
    - libsasl2-dev
    - libldap-dev
    - python-dev
    - libpython-dev
    - python-setuptools
    - virtualenv
    - python-virtualenv
    - python-pip

- name: "PIP install modules in virtualenv {{ aedir_prefix }}"
  pip:
    name: "{{ item }}"
    state: latest
    virtualenv: "{{ aedir_prefix }}"
    virtualenv_site_packages: yes
    extra_args: "--upgrade"
  with_items:
    - python-ldap
    - pyasn1
    - pyasn1_modules
    - aedir
    - slapdsock
    - netaddr

- name: "Install additional base packages on {{ openldap_role }} on {{ ansible_lsb.id }}"
  apt:
    name: "{{ item }}"
    state: installed
    update_cache: no
    install_recommends: no
    dpkg_options: 'force-confold,force-confdef'
  with_items:
    - python-paramiko
    - python-webpy
  when: openldap_role=="provider"

- name: "PIP install additional modules on {{ openldap_role }} on {{ ansible_lsb.id }}"
  pip:
    name: "{{ item }}"
    state: latest
    virtualenv: "{{ aedir_prefix }}"
    virtualenv_site_packages: yes
    extra_args: "--upgrade"
  with_items:
    - mailutil
    - oath
    - passlib
  when: openldap_role=="provider"
