---

- name: "Install C compiler packages on {{ lsb_id }}"
  apt:
    name:
      - gcc
      - libssl-dev
      - libsasl2-dev
      - libldap-dev
      - python-dev
      - libpython-dev
      - libffi-dev
    state: present
    update_cache: yes
    cache_valid_time: 3600
    install_recommends: no
    dpkg_options: 'force-confold,force-confdef'
  when: aedir_pip_needs_compiler==True

- name: "Install base packages on {{ lsb_id }}"
  apt:
    name:
      - python-setuptools
      - virtualenv
      - python-virtualenv
      - python-pip
      - python-cffi
    state: present
    update_cache: no
    install_recommends: no
    dpkg_options: 'force-confold,force-confdef'
  notify:
    - restart ae-dir-pwd
    - restart hotp_validator
    - restart oathenroll
    - restart bind_proxy
    - restart web2ldap

- name: "AE-DIR tools installation in virtualenv {{ aedir_prefix }}"
  include_tasks: "aedir_tools_venv.yml"
