---

- name: "Prepare virtualenv {{ aedir_prefix }} for Python 3"
  pip:
    name:
      - pip
      - setuptools
    state: latest
    virtualenv: "{{ aedir_prefix }}"
    virtualenv_site_packages: no
    virtualenv_command: "pyvenv-{{ aedir_python_version }}"
    extra_args: "{{ aedir_pip_extra_args }}"

- name: "Additional PIP packages in virtualenv {{ aedir_prefix }}"
  pip:
    name:
      - cryptography
      - asn1crypto
      - jwcrypto
      - pyasn1>=0.4.5
      - pyasn1_modules>=0.2.5
      - ldap0>=0.6.4
      - aedir>=0.7.1
      - prometheus_client>=0.7.1
    state: present
    virtualenv: "{{ aedir_prefix }}"
    extra_args: "{{ aedir_pip_extra_args }}"
  notify:
    - restart ae-dir-pwd
    - restart hotp_validator
    - restart oathenroll
    - restart bind_proxy
    - restart web2ldap

- name: "PIP package slapdsock in virtualenv {{ aedir_prefix }}"
  pip:
    name: slapdsock>=0.11.3
    state: present
    virtualenv: "{{ aedir_prefix }}"
    extra_args: "{{ aedir_pip_extra_args }}"
  notify:
    - restart hotp_validator
    - restart bind_proxy

- name: "PIP install additional modules in virtualenv {{ aedir_prefix }} on {{ openldap_role }}"
  pip:
    name:
      - mailutil>=0.4.0
      - paramiko
      - passlib
      - xlwt
      - dnspython
      - web.py<=0.40
    state: present
    virtualenv: "{{ aedir_prefix }}"
    extra_args: "{{ aedir_pip_extra_args }}"
  when: openldap_role == 'provider'
  notify:
    - restart ae-dir-pwd
    - restart oathenroll
    - restart hotp_validator
    - restart web2ldap

- name: "PIP install aedir_pproc in virtualenv {{ aedir_prefix }} on {{ openldap_role }} on {{ lsb_id }}"
  pip:
    name:
      - aedir_pproc>=0.4.3
    state: present
    virtualenv: "{{ aedir_prefix }}"
    extra_args: "{{ aedir_pip_extra_args }}"
  when: openldap_role == 'provider'
  notify:
    - restart ae-dir-pwd
