---

- name: "Install base packages on {{ lsb_id }}"
  zypper:
    name:
      - python-pyasn1>=0.3.7
      - python-pyasn1-modules>=0.1.5
      - python-ldap0==0.2.7
      - python-aedir==0.3.0
      - python-cryptography
      - python-jwcrypto
    state: present
    disable_recommends: yes
    type: package
  notify:
    - restart ae-dir-pwd
    - restart hotp_validator
    - restart oathenroll
    - restart bind_proxy
    - restart web2ldap

- name: "Install python-slapdsock packages on {{ lsb_id }}"
  zypper:
    name: python-slapdsock==0.10.0
    state: present
    disable_recommends: yes
    type: package
  notify:
    - restart hotp_validator
    - restart bind_proxy

- name: "Install additional packages on {{ openldap_role }} on {{ lsb_id }}"
  zypper:
    name:
      - python-paramiko
      - python-mailutil==0.2.0
      - python-passlib
      - python-asn1crypto
      - python-xlwt
      - python-pycryptodome
    state: present
    disable_recommends: yes
    type: package
  when: openldap_role == 'provider'
  notify:
    - restart ae-dir-pwd
    - restart oathenroll
    - restart hotp_validator
    - restart web2ldap

- name: "Install ae-dir-cli on {{ openldap_role }} on {{ lsb_id }}"
  zypper:
    name:
      - ae-dir-cli==0.1.1
    state: present
    disable_recommends: yes
    type: package
  when: openldap_role == 'provider'

- name: "Install ae-dir-pproc on {{ openldap_role }} on {{ lsb_id }}"
  zypper:
    name:
      - ae-dir-pproc>=0.1.2
    state: present
    disable_recommends: yes
    type: package
  when: openldap_role == 'provider'
  notify:
    - restart ae-dir-pwd

- name: "Install web2ldap on {{ openldap_role }} on {{ lsb_id }}"
  zypper:
    name:
      - web2ldap<1.5
    state: present
    disable_recommends: yes
    type: package
  when: openldap_role == 'provider'
  notify:
    - restart web2ldap

- name: "Install additional packages for simple web apps on {{ openldap_role }} on {{ lsb_id }}"
  zypper:
    name:
      - python-web.py<=0.40
    state: present
    disable_recommends: yes
    type: package
  when: openldap_role == 'provider'
  notify:
    - restart ae-dir-pwd
    - restart oathenroll

- name: "Install additional packages for web2ldap on {{ openldap_role }} on {{ lsb_id }}"
  zypper:
    name:
      - python-dnspython
    state: present
    disable_recommends: yes
    type: package
  when: openldap_role == 'provider'
  notify:
    - restart web2ldap
