---

- name: "Install base packages on {{ lsb_id }}"
  zypper:
    name:
      - python-pyasn1>=0.3.7
      - python-pyasn1-modules>=0.1.5
      - python-ldap0>=0.1.1
      - python-aedir>=0.2.0
      - python-cryptography
      - python-jwcrypto
    state: present
    disable_recommends: yes
    type: package
  notify:
    - restart aedirpwd
    - restart hotp_validator
    - restart oathenroll
    - restart bind_proxy
    - restart web2ldap

- name: "Install python-slapdsock packages on {{ lsb_id }}"
  zypper:
    name: python-slapdsock
    state: present
    disable_recommends: yes
    type: package
  notify:
    - restart hotp_validator
    - restart bind_proxy

- name: "Install additional packages on {{ openldap_role }} on {{ lsb_id }}"
  zypper:
    name:
      - python-paramiko
      - python-mailutil
      - python-passlib
      - python-asn1crypto
      - python-xlwt
      - python-pycryptodome
      - web2ldap>=1.3.36
    state: present
    disable_recommends: yes
    type: package
  when: openldap_role == 'provider'
  notify:
    - restart aedirpwd
    - restart oathenroll
    - restart hotp_validator
    - restart web2ldap

- name: "Install additional packages for simple web apps on {{ openldap_role }} on {{ lsb_id }}"
  zypper:
    name:
      - python-web.py
    state: present
    disable_recommends: yes
    type: package
  when: openldap_role == 'provider'
  notify:
    - restart aedirpwd
    - restart oathenroll

- name: "Install additional packages for web2ldap on {{ openldap_role }} on {{ lsb_id }}"
  zypper:
    name:
      - python-pyweblib>=1.3.13
      - python-dnspython
      - python-certifi
    state: present
    disable_recommends: yes
    type: package
  when: openldap_role == 'provider'
  notify:
    - restart web2ldap
