---

- name: "Install Python 3 modules on {{ lsb_id }}"
  zypper:
    name:
      - python3-pyasn1 >= 0.4.8
      - python3-pyasn1-modules >= 0.2.8
      - python3-ldap0 >= 1.2.11
      - python3-aedir >= 1.4.8
      - python3-cffi
      - python3-cryptography
      - python3-asn1crypto >= 1.4.0
      - python3-jwcrypto >= 0.9.1
      - python3-psutil >= 5.6.7
      - python3-prometheus_client >= 0.11.0
      - python3-python-dateutil
      - python3-defusedxml
      - python3-gunicorn >= 20.0.4
    state: present
    disable_recommends: yes
    type: package
  notify:
    - restart ae-dir-pwd
    - restart hotp_validator
    - restart oathenroll
    - restart bind_proxy
    - restart web2ldap

- name: "Install python3-slapdsock packages on {{ lsb_id }}"
  zypper:
    name: python3-slapdsock >= 1.1.0
    state: present
    disable_recommends: yes
    type: package
  notify:
    - restart hotp_validator
    - restart bind_proxy

- name: "Install additional packages on provider"
  zypper:
    name:
      - python3-paramiko
      - python3-mailutil >= 0.4.0
      - python3-xlwt
      - python3-pycryptodome
      - python3-PyNaCl >= 1.2
    state: present
    disable_recommends: yes
    type: package
  when: openldap_role == 'provider'
  notify:
    - restart ae-dir-pwd
    - restart oathenroll
    - restart hotp_validator
    - restart web2ldap

- name: "Install ae-dir-tool on provider"
  zypper:
    name:
      - ae-dir-tool >= 1.0.6
    state: present
    disable_recommends: yes
    type: package
  when: openldap_role == 'provider'

- name: "Install additional packages for Flask web apps on {{ openldap_role }}"
  zypper:
    name:
      - python3-Flask >= 1.1.0
      - python3-Jinja2 >= 2.10.0
      - python3-Werkzeug >= 1.0.0
      - python3-WTForms >= 2.2.0
    state: present
    disable_recommends: yes
    type: package
  when: openldap_role == 'provider'
  notify:
    - "restart flask-apps"

- name: "Install ae-dir-pproc on provider"
  zypper:
    name:
      - ae-dir-pproc >= 1.5.5
    state: present
    disable_recommends: yes
    type: package
  when: openldap_role == 'provider'
  notify:
    - restart ae-dir-pwd
