---

- name: "Install Python 3 modules on {{ lsb_id }}"
  zypper:
    name:
      - python3-pyasn1 >= 0.4.5
      - python3-pyasn1-modules >= 0.2.5
      - python3-ldap0 >= 0.6.6
      - python3-aedir >= 0.8.0
      - python3-cryptography
      - python3-asn1crypto
      - python3-jwcrypto
      - python3-psutil >= 5.6.7
      - python3-prometheus_client >= 0.7.1
    state: present
    disable_recommends: yes
    type: package
  notify:
    - restart ae-dir-pwd
    - restart hotp_validator
    - restart oathenroll
    - restart bind_proxy
    - restart web2ldap

- name: "Install python3-slapdsock packages on {{ lsb_id }}"
  zypper:
    name: python3-slapdsock >= 0.11.4
    state: present
    disable_recommends: yes
    type: package
  notify:
    - restart hotp_validator
    - restart bind_proxy

- name: "Install additional packages on {{ openldap_role }} on {{ lsb_id }}"
  zypper:
    name:
      - python3-paramiko
      - python3-mailutil >= 0.4.0
      - python3-passlib
      - python3-xlwt
      - python3-pycryptodome
    state: present
    disable_recommends: yes
    type: package
  when: openldap_role == 'provider'
  notify:
    - restart ae-dir-pwd
    - restart oathenroll
    - restart hotp_validator
    - restart web2ldap

- name: "Install ae-dir-pproc on {{ openldap_role }} on {{ lsb_id }}"
  zypper:
    name:
      - ae-dir-pproc >= 0.5.0
    state: present
    disable_recommends: yes
    type: package
  when: openldap_role == 'provider'
  notify:
    - restart ae-dir-pwd

- name: "Install additional packages for simple web apps on {{ openldap_role }} on {{ lsb_id }}"
  zypper:
    name:
      - python3-web.py >= 0.40
    state: present
    disable_recommends: yes
    type: package
  when: openldap_role == 'provider'
  notify:
    - restart ae-dir-pwd
    - restart oathenroll

- name: "Install additional packages for web2ldap on {{ openldap_role }} on {{ lsb_id }}"
  zypper:
    name:
      - python3-dnspython
    state: present
    disable_recommends: yes
    type: package
  when: openldap_role == 'provider'
  notify:
    - restart web2ldap
