---

- name: "Install base packages on {{ lsb_id }}"
  zypper:
    name: "{{ item }}"
    state: present
    disable_recommends: yes
    type: package
  with_items:
    - python-aedir
    - python-ldap=2.5.2
    - python-pyasn1>=0.3.7
    - python-pyasn1-modules>=0.1.5
    - python-netaddr
    - python-jwcrypto
  notify:
    - restart aedirpwd
    - restart hotp_validator
    - restart oathenroll
    - restart bind_proxy
    - restart web2ldap

- name: "Install python-slapdsock packages on {{ lsb_id }}"
  zypper:
    name: python-slapdsock
    state: present
    disable_recommends: yes
    type: package
  notify:
    - restart hotp_validator
    - restart bind_proxy

- name: "Install additional packages on {{ openldap_role }} on {{ lsb_id }}"
  zypper:
    name: "{{ item }}"
    state: present
    disable_recommends: yes
    type: package
  with_items:
    - python-paramiko
    - python-mailutil
    - python-web.py
    - python-passlib
    - python-pyweblib
  when: openldap_role == 'provider'
  notify:
    - restart aedirpwd
    - restart oathenroll
    - restart hotp_validator
