---

- name: "Check for Python version in virtualenv {{ aedir_prefix }}"
  command: "{{ aedir_bin }}/python --version"
  ignore_errors: yes
  register: current_venv_python_version

- name: "Remove stale virtualenv {{ aedir_prefix }}"
  file:
    path: "{{ item }}"
    state: absent
  ignore_errors: yes
  loop:
    - "{{ aedir_bin }}"
    - "{{ aedir_prefix }}/include"
    - "{{ aedir_prefix }}/lib"
    - "{{ aedir_prefix }}/lib64"
    - "{{ aedir_prefix }}/share"
    - "{{ aedir_prefix }}/pip-selfcheck.json"
    - "{{ aedir_prefix }}/pyvenv.cfg"
  when: not current_venv_python_version.stdout[7:].startswith(aedir_python_version)

- name: "Prepare virtualenv {{ aedir_prefix }} for Python"
  pip:
    name:
      - pip
      - setuptools
    state: latest
    virtualenv: "{{ aedir_prefix }}"
    virtualenv_site_packages: no
    virtualenv_command: "{{ virtualenv_command }}"
    extra_args: "{{ aedir_pip_extra_args }}"

- name: "Additional PIP packages in virtualenv {{ aedir_prefix }}"
  pip:
    name:
      - cffi
      - cryptography
      - asn1crypto>=1.4.0
      - jwcrypto>=0.9.1
      - pyasn1>=0.4.8
      - pyasn1_modules>=0.2.8
      - ldap0>=1.4.3
      - aedir>=1.4.11
      - psutil>=5.6.7
      - prometheus_client>=0.11.0
      - python-dateutil
      - defusedxml
    state: present
    virtualenv: "{{ aedir_prefix }}"
    extra_args: "{{ aedir_pip_extra_args }}"
  environment:
    LDFLAGS: "-fuse-ld=bfd"
    LIBLDAP0_INCLUDE_DIRS: "{{ openldap_path.prefix }}/include"
    LIBLDAP0_LIBRARY_DIRS: "{{ openldap_path.libdir }}"
    LIBLDAP0_LIBS: "ldap"
  notify:
    - restart ae-dir-pwd
    - restart hotp_validator
    - restart oathenroll
    - restart bind_proxy
    - restart web2ldap

- name: "PIP package slapdsock in virtualenv {{ aedir_prefix }}"
  pip:
    name: slapdsock>=1.3.0
    state: present
    virtualenv: "{{ aedir_prefix }}"
    extra_args: "{{ aedir_pip_extra_args }}"
  notify:
    - restart hotp_validator
    - restart bind_proxy

- name: "PIP install additional modules in virtualenv {{ aedir_prefix }}"
  pip:
    name:
      - gunicorn>=20.0.4
      - mailutil>=0.4.0
      - paramiko
      - xlwt
      - pynacl>=1.2
    state: present
    virtualenv: "{{ aedir_prefix }}"
    extra_args: "{{ aedir_pip_extra_args }}"
  when: openldap_role == 'provider'
  notify:
    - restart ae-dir-pwd
    - restart oathenroll
    - restart hotp_validator
    - restart web2ldap

- name: "PIP install ae-dir-tool in virtualenv on provider"
  pip:
    name:
      - ae-dir-tool>=1.0.8
    state: present
    virtualenv: "{{ aedir_prefix }}"
    extra_args: "{{ aedir_pip_extra_args }}"
  when: openldap_role == 'provider'

- name: "PIP install additional modules for Flask web apps"
  pip:
    name:
      - Flask>=2.0.1
      - Jinja2>=3.0.1
      - Werkzeug>=2.0.1
      - WTForms>=2.3.3
      - itsdangerous>=2.0.0
    state: present
    virtualenv: "{{ aedir_prefix }}"
    extra_args: "{{ aedir_pip_extra_args }}"
  when: openldap_role == 'provider'
  notify:
    - "restart flask-apps"

- name: "PIP install aedir_pproc in virtualenv on provider"
  pip:
    name:
      - ae-dir-pproc>=1.7.0
    state: present
    virtualenv: "{{ aedir_prefix }}"
    extra_args: "{{ aedir_pip_extra_args }}"
  when: openldap_role == 'provider'
  notify:
    - restart ae-dir-pwd
