---

- name: "Check whether all C wrapper modules are installed"
  pip:
    name:
      - ldap0>=1.4.3
      - psutil>=5.6.7
    state: present
    virtualenv: "{{ aedir_prefix }}"
    extra_args: "{{ aedir_pip_extra_args }}"
  ignore_errors: yes
  when: aedir_pip_install
  register: ldap0_installed

- name: "Install C compiler packages"
  yum:
    name:
      - gcc
      - openssl-devel
      - cyrus-sasl-devel
      - openldap-devel
      - python3-devel
      - libffi-devel
    state: present
    update_cache: no
  when: aedir_pip_install_compiler is defined or ldap0_installed.failed

- name: "Install Python 3 packages"
  yum:
    name:
      - python3-setuptools
      - python3-pip
    state: present
    update_cache: no
  notify:
    - "restart python-services"

- name: "AE-DIR tools installation in virtualenv {{ aedir_prefix }}"
  include_tasks: "aedir_tools_venv.yml"

- name: "Uninstall C compiler packages"
  yum:
    name:
      - gcc
      - openssl-devel
      - cyrus-sasl-devel
      - openldap-devel
      - python3-devel
      - libffi-devel
    state: absent
    autoremove: yes
    update_cache: no
