---
# Tasks on providers after AE-DIR tools installation

- name: "Install backup script"
  template:
    src: "scripts/ae-dir-slapcat.sh.j2"
    dest: "{{ aedir_sbin }}/ae-dir-slapcat.sh"
    owner: root
    group: root
    mode: 0o0750
