---

- name: "Check whether all C wrapper modules are installed"
  pip:
    name:
      - ldap0>=1.4.3
      - psutil>=5.6.7
    state: present
    virtualenv: "{{ aedir_prefix }}"
    extra_args: "{{ aedir_pip_extra_args }}"
  ignore_errors: yes
  when: aedir_pip_install
  register: ldap0_installed

- name: "Install Python {{ aedir_python_version }} packages on {{ lsb_id }}"
  apt:
    name:
      - "libpython{{ aedir_python_version }}"
      - "python{{ aedir_python_version }}-venv"
      - python3-setuptools
      - python3-pip
    state: present
    update_cache: no
    install_recommends: no
    dpkg_options: 'force-confold,force-confdef'
  notify:
    - restart ae-dir-pwd
    - restart hotp_validator
    - restart oathenroll
    - restart bind_proxy
    - restart web2ldap

- name: "Install C compiler packages on {{ lsb_id }}"
  apt:
    name:
      - gcc
      - cpp
      - libssl-dev
      - libsasl2-dev
      - python3-dev
      - libpython3-dev
      - libffi-dev
    state: present
    update_cache: no
    install_recommends: no
    dpkg_options: 'force-confold,force-confdef'
  when: aedir_pip_install_compiler is defined or ldap0_installed.failed

- name: "Generate /etc/python{{ aedir_python_version }}/sitecustomize.py"
  copy:
    content: "# Managed by ansible!\n# Deliberately empty!\n# Do not edit!\n"
    dest: "/etc/python{{ aedir_python_version }}/sitecustomize.py"
    owner: root
    group: root
    mode: 0o0644

- name: "AE-DIR tools installation in virtualenv {{ aedir_prefix }}"
  include_tasks: "aedir_tools_venv.yml"

- name: "Uninstall C compiler packages on {{ lsb_id }}"
  apt:
    name:
      - gcc
      - cpp
      - libssl-dev
      - libsasl2-dev
      - libldap2-dev
      - python3-dev
      - libpython3-dev
      - libffi-dev
    state: absent
    autoremove: yes
    update_cache: no
    dpkg_options: 'force-confold,force-confdef'
