---

- name: "Install C compiler packages on {{ lsb_id }}"
  apt:
    name: "{{ item }}"
    state: installed
    update_cache: no
    install_recommends: no
    dpkg_options: 'force-confold,force-confdef'
  with_items:
    - gcc
    - libssl-dev
    - libsasl2-dev
    - libldap-dev
    - python-dev
    - libpython-dev
    - libffi-dev
  when: aedir_pip_needs_compiler==True

- name: "Install base packages on {{ lsb_id }}"
  apt:
    name: "{{ item }}"
    state: installed
    update_cache: no
    install_recommends: no
    dpkg_options: 'force-confold,force-confdef'
  with_items:
    - cron
    - tar
    - gzip
    - python-setuptools
    - virtualenv
    - python-virtualenv
    - python-pip
    - python-cffi
  notify:
    - restart aedirpwd
    - restart hotp_validator
    - restart oathenroll
    - restart bind_proxy

- name: "Additional PIP packages in virtualenv {{ aedir_prefix }} needed for PIP installation"
  pip:
    name: "{{ item }}"
    state: present
    virtualenv: "{{ aedir_prefix }}"
    virtualenv_site_packages: no
    extra_args: "{{ aedir_pip_extra_args }}"
  with_items:
    - pip
    - setuptools

- name: "Additional PIP packages in virtualenv {{ aedir_prefix }}"
  pip:
    name: "{{ item }}"
    state: present
    virtualenv: "{{ aedir_prefix }}"
    virtualenv_site_packages: no
    extra_args: "{{ aedir_pip_extra_args }}"
  with_items:
    - pyasn1
    - pyasn1_modules
    - python-ldap
    - aedir
    - slapdsock
    - netaddr
    - cryptography
    - jwcrypto
  notify:
    - restart aedirpwd
    - restart hotp_validator
    - restart oathenroll
    - restart bind_proxy

- name: "PIP install additional modules in virtualenv {{ aedir_prefix }} on {{ openldap_role }} on {{ lsb_id }}"
  pip:
    name: "{{ item }}"
    state: latest
    virtualenv: "{{ aedir_prefix }}"
    virtualenv_site_packages: yes
    extra_args: "{{ aedir_pip_extra_args }}"
  with_items:
    - mailutil
    - paramiko
    - web.py
    - oath
    - passlib
  when: openldap_role == 'provider'
  notify:
    - restart aedirpwd
    - restart oathenroll
    - restart hotp_validator
