---
# Tasks on providers after AE-DIR tools installation

- name: "Create ae-dir-base.ldif"
  template:
    src: "ae-dir-base.ldif.j2"
    dest: "{{ aedir_etc }}/ae-dir-base.ldif"
    owner: root
    group: root
    mode: 0600
  when: aedir_init == True

- name: "Install tool scripts"
  template:
    src: "scripts/{{ item }}.j2"
    dest: "{{ aedir_bin }}/{{ item }}"
    owner: root
    group: root
    mode: 0755
  with_items:
    - ae-add-zone.py
    - ae-passwd.py
    - ae-person-report.py
    - ae-set-next-gid.py
    - ae-user-report.py

- name: "Install backup script from template"
  template:
    src: "scripts/ae-dir-slapcat.sh.j2"
    dest: "{{ aedir_sbin }}/ae-dir-slapcat.sh"
    owner: root
    group: root
    mode: 0750

- name: "set env var HOME={{ aedir_rundir }} in /etc/cron.d/aedir_update"
  cron:
    env: yes
    name: "HOME"
    value: "{{ aedir_rundir }}"
    state: present
    user: root
    cron_file: aedir_update

- name: "set env var LDAPRC={{ aedir_etc }}/ldap.conf in /etc/cron.d/aedir_update"
  cron:
    env: yes
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    user: root
    cron_file: aedir_update
  with_dict:
    LDAPRC: "{{ aedir_etc }}/ldap.conf"
    PYTHONOPTIMIZE: "2"
    PYTHONDONTWRITEBYTECODE: "1"

- name: "Run aedir_update_groups.py as CRON job"
  cron:
    name: "aedir_update_groups"
    state: present
    user: root
    cron_file: aedir_update
    minute: "*/3"
    job: "{{ aedir_python }} -m aedir_update.groups"

- name: "Run aedir_update.status as CRON job"
  cron:
    name: "aedir_update_status"
    state: present
    user: root
    cron_file: aedir_update
    minute: "*/13"
    job: "{{ aedir_python }} -m aedir_update.status"

- name: "Run aedir_update.persattrs as CRON job"
  cron:
    name: "aedir_update_persattrs"
    state: present
    user: root
    cron_file: aedir_update
    minute: "*/2"
    job: "{{ aedir_python }} -m aedir_update.persattrs {{ aedir_rundir }}/aedir_update_persattrs.state"

- name: "Reset aedir_update.persattrs as CRON job"
  cron:
    name: "reset_aedir_update_persattrs"
    state: present
    user: root
    cron_file: aedir_update
    hour: "*/12"
    job: "rm {{ aedir_rundir }}/aedir_update_persattrs.state > /dev/null 2>&1 || exit 0"
