---

- name: "add zypper repository devel_languages_python"
  zypper_repository:
    name: devel_languages_python
    description: "Python modules"
    state: present
    enabled: yes
    auto_import_keys: yes
    autorefresh: yes
    disable_gpg_check: no
    overwrite_multiple: yes
    repo: "http://download.opensuse.org/repositories/devel:/languages:/python/openSUSE_Tumbleweed/"

- name: "Install base packages on {{ ansible_lsb.id }}"
  zypper:
    name: "{{ item }}"
    state: present
    disable_recommends: yes
    type: package
  with_items:
    - cron
    - python
    - python-aedir
    - python-ldap
    - python-pyasn1
    - python-pyasn1-modules
    - python-slapdsock

- name: "Install additional base packages for web applications on {{ ansible_lsb.id }}"
  zypper:
    name: "{{ item }}"
    state: present
    disable_recommends: yes
    type: package
  notify:
    - "restart {{ web_server }}"
    - restart web2ldap
  with_items:
    - python-paramiko
    - python-mailutil
    - python-web.py
  when: openldap_role=="provider"
