---

- name: "Install C compiler packages on {{ lsb_id }}"
  yum:
    name:
      - gcc
      - openssl-devel
      - cyrus-sasl-devel
      - openldap-devel
      - python-devel
      - libffi-devel
    state: present
    update_cache: yes
  when: aedir_pip_needs_compiler==True

- name: "Install base packages on {{ lsb_id }}"
  yum:
    name:
      - python-setuptools
      - python-virtualenv
      - python-pip
      - python-cffi
    state: present
    update_cache: yes
  notify:
    - restart aedirpwd
    - restart hotp_validator
    - restart oathenroll
    - restart bind_proxy
    - restart web2ldap

- name: "AE-DIR tools installation in virtualenv {{ aedir_prefix }}"
  include_tasks: "aedir_tools_venv.yml"
