---

- name: "Install base packages on {{ lsb_id }}"
  zypper:
    name: "{{ item }}"
    state: present
    disable_recommends: yes
    type: package
  with_items:
    - python-pyasn1>=0.3.7
    - python-pyasn1-modules>=0.1.5
    - python-ldap0
    - python-aedir
    - python-cryptography
    - python-jwcrypto
    - python-virtualenv
  notify:
    - restart aedirpwd
    - restart hotp_validator
    - restart oathenroll
    - restart bind_proxy
    - restart web2ldap

- name: "Install python-slapdsock packages on {{ lsb_id }}"
  zypper:
    name: python-slapdsock
    state: present
    disable_recommends: yes
    type: package
  notify:
    - restart hotp_validator
    - restart bind_proxy

- name: "Install additional packages on {{ openldap_role }} on {{ lsb_id }}"
  zypper:
    name: "{{ item }}"
    state: present
    disable_recommends: yes
    type: package
  with_items:
    - python-paramiko
    - python-mailutil
    - python-passlib
    - python-asn1crypto
    - python-xlwt
    - python-pycryptodome
    - web2ldap
  when: openldap_role == 'provider'
  notify:
    - restart aedirpwd
    - restart oathenroll
    - restart hotp_validator
    - restart web2ldap

- name: "Install additional packages for simple web apps on {{ openldap_role }} on {{ lsb_id }}"
  zypper:
    name: "{{ item }}"
    state: present
    disable_recommends: yes
    type: package
  with_items:
    - python-web.py
  when: openldap_role == 'provider'
  notify:
    - restart aedirpwd
    - restart oathenroll

- name: "Install additional packages for web2ldap on {{ openldap_role }} on {{ lsb_id }}"
  zypper:
    name: "{{ item }}"
    state: present
    disable_recommends: yes
    type: package
  with_items:
    - python-pyweblib>=1.3.13
    - python-dnspython
    - python-certifi
  when: openldap_role == 'provider'
  notify:
    - restart web2ldap
