---
# Tasks on providers after AE-DIR tools installation

- name: "Create ae-dir-base.ldif"
  template:
    src: "ae-dir-base.ldif.j2"
    dest: "{{ aedir_etc }}/ae-dir-base.ldif"
    owner: root
    group: root
    mode: 0600
  when: aedir_init == True

- name: "Install tool scripts"
  template:
    src: "scripts/{{ item }}.j2"
    dest: "{{ aedir_bin }}/{{ item }}"
    owner: root
    group: root
    mode: 0755
  with_items:
    - ae-add-zone.py
    - ae-passwd.py
    - ae-person-report.py
    - ae-set-next-gid.py
    - ae-user-report.py

- name: "Install backup script from template"
  template:
    src: "scripts/ae-dir-slapcat.sh.j2"
    dest: "{{ aedir_sbin }}/ae-dir-slapcat.sh"
    owner: root
    group: root
    mode: 0750

- name: "set env var HOME={{ aedir_rundir }} in /etc/cron.d/{{ aedir_cron_file }}"
  cron:
    env: yes
    name: "HOME"
    value: "{{ aedir_rundir }}"
    state: present
    user: root
    cron_file: "{{ aedir_cron_file }}"

- name: "Set env vars in {{ aedir_cron_file }}"
  cron:
    env: yes
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    user: root
    cron_file: "{{ aedir_cron_file }}"
  with_dict:
    LDAPRC: "{{ aedir_etc }}/ldap.conf"
    PYTHONOPTIMIZE: "2"
    PYTHONDONTWRITEBYTECODE: "1"

- name: "Install provider Python-based CRON jobs"
  cron:
    name: "{{ item.key }}"
    state: present
    user: root
    cron_file: "{{ aedir_cron_file }}"
    hour: "{{ item.value['hour']|default('*') }}"
    minute: "{{ item.value.minute }}"
    job: "{{ aedir_python }} -m {{ item.value.pyjob }}"
  with_dict:
    aedir_pproc_groups:
      minute: "*/3"
      pyjob: aedir_pproc.groups
    aedir_pproc_status:
      minute: "*/13"
      pyjob: "aedir_pproc.status"
    aedir_pproc_persattrs:
      minute: "*/2"
      pyjob: "aedir_pproc.persattrs {{ aedir_rundir }}/aedir_pproc_persattrs.state"
