---

- name: "Prepare virtualenv {{ aedir_prefix }} for Python 3"
  pip:
    name:
      - pip
      - setuptools
    state: latest
    virtualenv: "{{ aedir_prefix }}"
    virtualenv_site_packages: no
    virtualenv_command: "{{ virtualenv_command }}"
    extra_args: "{{ aedir_pip_extra_args }}"

- name: "Additional PIP packages in virtualenv {{ aedir_prefix }}"
  pip:
    name:
      - cffi
      - cryptography
      - asn1crypto>=1.4.0
      - jwcrypto
      - pyasn1>=0.4.8
      - pyasn1_modules>=0.2.8
      - ldap0>=1.2.8
      - aedir>=1.4.6
      - psutil>=5.6.7
      - prometheus_client>=0.7.1
      - python-dateutil
      - defusedxml
      - gunicorn>=20.0.4
    state: present
    virtualenv: "{{ aedir_prefix }}"
    extra_args: "{{ aedir_pip_extra_args }}"
  environment:
    LDFLAGS: "-fuse-ld=bfd"
  notify:
    - restart ae-dir-pwd
    - restart hotp_validator
    - restart oathenroll
    - restart bind_proxy
    - restart web2ldap

- name: "PIP package slapdsock in virtualenv {{ aedir_prefix }}"
  pip:
    name: slapdsock>=1.1.0
    state: present
    virtualenv: "{{ aedir_prefix }}"
    extra_args: "{{ aedir_pip_extra_args }}"
  notify:
    - restart hotp_validator
    - restart bind_proxy

- name: "PIP install additional modules in virtualenv {{ aedir_prefix }} on {{ openldap_role }}"
  pip:
    name:
      - mailutil>=0.4.0
      - paramiko
      - passlib
      - xlwt
      - pynacl>=1.2
    state: present
    virtualenv: "{{ aedir_prefix }}"
    extra_args: "{{ aedir_pip_extra_args }}"
  when: openldap_role == 'provider'
  notify:
    - restart ae-dir-pwd
    - restart oathenroll
    - restart hotp_validator
    - restart web2ldap

- name: "PIP install ae-dir-tool in virtualenv on provider"
  pip:
    name:
      - ae-dir-tool>=1.0.6
    state: present
    virtualenv: "{{ aedir_prefix }}"
    extra_args: "{{ aedir_pip_extra_args }}"
  when: openldap_role == 'provider'

- name: "PIP install additional modules for Flask web apps on {{ openldap_role }}"
  pip:
    name:
      - Flask>=1.1.0
      - Jinja2>=2.10.0
      - Werkzeug>=1.0.0
      - WTForms>=2.2.0
    state: present
    virtualenv: "{{ aedir_prefix }}"
    extra_args: "{{ aedir_pip_extra_args }}"
  when: openldap_role == 'provider'
  notify:
    - "restart flask-apps"

- name: "PIP install aedir_pproc in virtualenv on provider"
  pip:
    name:
      - aedir_pproc>=1.5.0
    state: present
    virtualenv: "{{ aedir_prefix }}"
    extra_args: "{{ aedir_pip_extra_args }}"
  when: openldap_role == 'provider'
  notify:
    - restart ae-dir-pwd
