---

- name: "Install base packages on {{ lsb_id }}"
  zypper:
    name: "{{ item }}"
    state: present
    disable_recommends: yes
    type: package
  with_items:
    - python-pyasn1>=0.3.7
    - python-pyasn1-modules>=0.1.5
    - python-ldap0
    - python-aedir
    - python-cryptography
    - python-jwcrypto
    - python-virtualenv
  notify:
    - restart aedirpwd
    - restart hotp_validator
    - restart oathenroll
    - restart bind_proxy
    - restart web2ldap

- name: "Install python-slapdsock packages on {{ lsb_id }}"
  zypper:
    name: python-slapdsock
    state: present
    disable_recommends: yes
    type: package
  notify:
    - restart hotp_validator
    - restart bind_proxy

- name: "Install additional packages on {{ openldap_role }} on {{ lsb_id }}"
  zypper:
    name: "{{ item }}"
    state: present
    disable_recommends: yes
    type: package
  with_items:
    - python-paramiko
    - python-mailutil
    - python-web.py
    - python-passlib
    - python-pyweblib>=1.3.13
    - python-asn1crypto
    - python-xlwt
    - python-pycryptodome
    - python-dnspython
    - python-certifi
    - python-Pillow
  when: openldap_role == 'provider'
  notify:
    - restart aedirpwd
    - restart oathenroll
    - restart hotp_validator
    - restart web2ldap

- name: "Prepare Python 2.x virtualenv {{ aedir_prefix }}"
  pip:
    name:
      - pip
      - setuptools
    state: latest
    virtualenv: "{{ aedir_prefix }}"
    virtualenv_site_packages: yes
    virtualenv_python: python2.7
    extra_args: "{{ aedir_pip_extra_args }}"
