---
# Install AE-DIR password service (aedirpwd)

- name: "Create directories for aedirpwd"
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
  with_items:
    - "{{ aedir_etc }}/aedirpwd"
    - "{{ aedir_etc }}/aedirpwd/templates"
    - "{{ aedir_etc }}/aedirpwd/templates/en"

- name: "copy aedirpwd HTML templates to {{ aedir_etc }}/aedirpwd/templates"
  copy:
    src: "aedirpwd/templates/"
    dest: "{{ aedir_etc }}/aedirpwd/templates"
    follow: no
    owner: root
    group: root
    mode: u=rw,g=r,o=r
    directory_mode: u=rwx,g=rx,o=rx

- name: "Create aedirpwd_cnf.py"
  template:
    src: "{{ item }}"
    dest: "{{ aedir_etc }}/aedirpwd/aedirpwd_cnf.py"
    owner: root
    group: root
    mode: 0644
  with_first_found:
    - files:
       - "aedirpwd/aedirpwd_cnf.py.j2"
      paths: "{{ aedir_templates_dirs }}"
  notify:
    - "restart aedirpwd"

- name: "Install password service web application"
  copy:
    src: "aedirpwd/{{ item }}"
    dest: "{{ aedir_sbin }}/{{ item }}"
    owner: root
    group: "{{ aedirpwd_web_group }}"
    mode: 0750
  with_items:
    - aedirpwd_web.py
  notify:
    - "restart aedirpwd"

- name: "Install password service CRON scripts"
  copy:
    src: "aedirpwd/{{ item }}"
    dest: "{{ aedir_sbin }}/{{ item }}"
    owner: root
    group: "{{ aedirpwd_web_group }}"
    mode: 0750
  with_items:
    - aedirpwd_cron.py
    - aedirpwd_expiry_check.py

- name: Install systemd unit file from template
  template:
    src: "aedirpwd/aedirpwd.service.j2"
    dest: "{{ aedir_systemd_dir }}/aedirpwd.service"
    owner: root
    group: root
    mode: 0644
  notify:
    - reload systemd
    - "restart aedirpwd"
  when: aedir_service_manager=="systemd"

- name: "set env var PYTHONPATH={{ aedir_etc }}/aedirpwd in /etc/cron.d/aedirpwd"
  cron:
    env: yes
    name: "PYTHONPATH"
    value: "{{ aedir_etc }}/aedirpwd"
    state: present
    user: ae-dir-pwd
    cron_file: aedirpwd

- name: Run aedirpwd_cron as CRON job
  cron:
    name: "aedirpwd_cron"
    state: present
    user: ae-dir-pwd
    cron_file: aedirpwd
    minute: "*/2"
    job: "{{ aedir_python }} {{ aedir_sbin }}/aedirpwd_cron.py"

- name: "Run aedirpwd_expiry_check as CRON job"
  cron:
    name: "aedirpwd_expiry_check"
    state: present
    user: ae-dir-pwd
    cron_file: aedirpwd
    hour: "0"
    minute: "0"
    job: "{{ aedir_python }} {{ aedir_sbin }}/aedirpwd_expiry_check.py"
