---

- name: "Install base packages on {{ lsb_id }}"
  zypper:
    name: "{{ item }}"
    state: present
    disable_recommends: yes
    type: package
  with_items:
    - cron
    - python
    - python-aedir
    - python-ldap
    - python-pyasn1
    - python-pyasn1-modules
    - python-slapdsock
    - python-netaddr
    - python-jwcrypto
  notify:
    - restart aedirpwd
    - restart hotp_validator
    - restart oathenroll
    - restart bind_proxy

- name: "Install additional packages on {{ openldap_role }} on {{ lsb_id }}"
  zypper:
    name: "{{ item }}"
    state: present
    disable_recommends: yes
    type: package
  with_items:
    - python-paramiko
    - python-mailutil
    - python-web.py
    - python-oath
    - python-passlib
  when: openldap_role == 'provider'
  notify:
    - restart aedirpwd
    - restart oathenroll
    - restart hotp_validator
