---
# Install some AE-DIR script tools and documentation files

- name: "Create client config file {{ aedir_etc }}/ldap.conf from template"
  template:
    src: "ldap.conf.j2"
    dest: "{{ aedir_etc }}/ldap.conf"
    owner: root
    group: root
    mode: 0o0644
  notify:
    - "restart {{ openldap_service_name }}"

- name: "Create logging config file {{ aedir_etc }}/ae-logging.conf from template"
  template:
    src: "{{ aedir_logging_conf }}"
    dest: "{{ aedir_etc }}/ae-logging.conf"
    owner: root
    group: root
    mode: 0o0644
  notify:
    - "restart ae-dir-pwd"
    - "restart oathenroll"
    - "restart {{ oath_bind_listener }}"
    - "restart web2ldap"
    - "restart pwsync"

- name: "install CA cert for SMTP/STARTTLS to {{ smtp_cacert_pathname }}"
  copy:
    src: "{{ smtp_cacert_filename }}"
    dest: "{{ smtp_cacert_pathname }}"
    follow: no
    owner: root
    group: root
    mode: u=rw,g=r,o=r
    directory_mode: u=rwx,g=rx,o=rx

- name: "Install tool scripts to {{ aedir_sbin }}"
  template:
    src: "scripts/{{ item }}.j2"
    dest: "{{ aedir_sbin }}/{{ item }}"
    owner: root
    group: root
    mode: 0o0750
  loop:
    - "ae-dir-replica-reset.sh"
    - "ae-dir-compact-db.sh"
    - "ae-dir-fix-db-permissions.sh"
    - "ae-dir-slapindex.sh"

- name: "Create /etc/profile.d/ae-dir.sh"
  template:
    src: "templates/profile-ae-dir.sh.j2"
    dest: "/etc/profile.d/ae-dir.sh"
    owner: root
    group: root
    mode: 0o0644
