---

- name: "Install C compiler packages on {{ lsb_id }}"
  yum:
    name:
      - gcc
      - openssl-devel
      - cyrus-sasl-devel
      - openldap-devel
      - python-devel
      - libffi-devel
    state: present
    update_cache: no
  when: aedir_pip_needs_compiler==True

- name: "Install base packages on {{ lsb_id }}"
  yum:
    name:
      - python3-setuptools
      - python3-virtualenv
      - python3-pip
      - python3-cffi
    state: present
    update_cache: no
  notify:
    - restart ae-dir-pwd
    - restart hotp_validator
    - restart oathenroll
    - restart bind_proxy
    - restart web2ldap

- name: "AE-DIR tools installation in virtualenv {{ aedir_prefix }}"
  include_tasks: "aedir_tools_venv.yml"
