---

- name: "Prepare virtualenv {{ aedir_prefix }} needed for PIP installation"
  pip:
    name:
      - pip
      - setuptools
    state: latest
    virtualenv: "{{ aedir_prefix }}"
    virtualenv_site_packages: no
    virtualenv_python: python2.7
    extra_args: "{{ aedir_pip_extra_args }}"

- name: "Additional PIP packages in virtualenv {{ aedir_prefix }} on {{ lsb_id }}"
  pip:
    name:
      - cryptography
      - asn1crypto
      - jwcrypto
      - pyasn1
      - pyasn1_modules
      - ldap0==0.2.7
      - aedir==0.3.0
    state: present
    virtualenv: "{{ aedir_prefix }}"
    virtualenv_python: python2.7
    extra_args: "{{ aedir_pip_extra_args }}"
  notify:
    - restart ae-dir-pwd
    - restart hotp_validator
    - restart oathenroll
    - restart bind_proxy
    - restart web2ldap

- name: "PIP package slapdsock in virtualenv {{ aedir_prefix }}"
  pip:
    name: slapdsock==0.10.0
    state: present
    virtualenv: "{{ aedir_prefix }}"
    extra_args: "{{ aedir_pip_extra_args }}"
  notify:
    - restart hotp_validator
    - restart bind_proxy

- name: "PIP install additional modules in virtualenv {{ aedir_prefix }} on {{ openldap_role }} on {{ lsb_id }}"
  pip:
    name:
      - mailutil==0.2.0
      - paramiko
      - passlib
      - xlwt
      - dnspython
      - web.py
    state: present
    virtualenv: "{{ aedir_prefix }}"
    extra_args: "{{ aedir_pip_extra_args }}"
  when: openldap_role == 'provider'
  notify:
    - restart ae-dir-pwd
    - restart oathenroll
    - restart hotp_validator
    - restart web2ldap

- name: "PIP install aedir_cli in virtualenv {{ aedir_prefix }} on {{ openldap_role }} on {{ lsb_id }}"
  pip:
    name:
      - aedir_cli==0.1.1
    state: present
    virtualenv: "{{ aedir_prefix }}"
    extra_args: "{{ aedir_pip_extra_args }}"
  when: openldap_role == 'provider'

- name: "PIP install ae-dir-pproc in virtualenv {{ aedir_prefix }} on {{ openldap_role }} on {{ lsb_id }}"
  pip:
    name:
      - aedir_pproc==0.1.1
    state: present
    virtualenv: "{{ aedir_prefix }}"
    extra_args: "{{ aedir_pip_extra_args }}"
  when: openldap_role == 'provider'
  notify:
    - restart ae-dir-pwd

- name: "PIP install web2ldap in virtualenv {{ aedir_prefix }} on {{ openldap_role }} on {{ lsb_id }}"
  pip:
    name:
      - web2ldap>=1.4.9
    state: present
    virtualenv: "{{ aedir_prefix }}"
    extra_args: "{{ aedir_pip_extra_args }}"
  when: openldap_role == 'provider'
  notify:
    - restart web2ldap
