---
# install and configure AppArmor

- name: "Install AppArmor packages"
  include_tasks: "apparmor_{{ lsb_id }}.yml"
  when: apparmor_enabled == True

- name: "Create AppArmor directories"
  file:
    path: "{{ apparmor_profiles_dir }}/{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0o0755
  loop:
    - "ae-dir"
    - "ae-dir/abstractions"
  notify:
    - "restart apparmor"

- name: "Create AppArmor abstractions files in {{ apparmor_profiles_dir }}/ae-dir/abstractions/"
  template:
    src: "apparmor/abstractions/{{ item }}.j2"
    dest: "{{ apparmor_profiles_dir }}/ae-dir/abstractions/{{ item }}"
    owner: root
    group: root
    mode: 0o0644
  loop:
    - base
    - ldapclient
    - nameservice
    - python
    - cli
    - gunicorn
  notify:
    - "restart apparmor"
    - "restart all-services"
