---
# install and activate AppArmor on openSUSE and SLE

- name: "Install AppArmor packages on {{ lsb_id }}"
  zypper:
    name:
      - apparmor-parser
      - apparmor-abstractions
    state: present
    disable_recommends: yes
    type: package
  notify:
    - restart apparmor
    - restart aedirpwd
    - restart hotp_validator
    - restart oathenroll
    - restart bind_proxy
    - restart web2ldap
    - "restart ae-slapd"
    - "restart ae-apache"
