---
# tasks file for roles/ae-dir-server

- name: "Install base OS packages"
  zypper:
    name: "{{ item }}"
    state: present
    disable_recommends: yes
    type: package
  with_items:
    - openssl
    - "{{ cron_pkg_name }}"
    - tar
    - gzip
    - ca-certificates
    - python
    - python-xml

- name: "Install alternative malloc package {{ aedir_malloc_package }}"
  zypper:
    name: "{{ aedir_malloc_package }}"
    state: present
    disable_recommends: yes
    type: package
  when: aedir_malloc_package!=""
