---
# tasks file for roles/ae-dir-server

- name: "Install base OS packages"
  zypper:
    name: "{{ item }}"
    state: present
    disable_recommends: yes
    type: package
  with_items:
    - openssl
    - cron
    - tar
    - gzip
    - ca-certificates
    - python
    - python-xml
