---
# tasks file for roles/ae-dir-server

- name: "Install base OS packages"
  zypper:
    name: "{{ item }}"
    state: present
    disable_recommends: yes
    type: package
  with_items:
    - openssl
    - "{{ cron_pkg_name }}"
    - tar
    - gzip
    - ca-certificates
    - python
    - python-xml
    - zypper

- name: "Install alternative malloc package {{ aedir_malloc_package }}"
  zypper:
    name: "{{ aedir_malloc_package }}"
    state: present
    disable_recommends: yes
    type: package
  when: aedir_malloc_package!=""

- name: "Add zypper repos for {{ ansible_lsb.description }}"
  zypper_repository:
    state: present
    enabled: yes
    overwrite_multiple: yes
    auto_import_keys: yes
    autorefresh: yes
    name: "{{ item.name }}"
    repo: "{{ item.repo }}"
  with_items: "{{ aedir_suse_repos[ansible_lsb.description] }}"

- name: "Refresh all repos on {{ ansible_lsb.description }}"
  zypper_repository:
    repo: '*'
    runrefresh: yes
