---
# Apply AE-DIR configuration to web2ldap

- name: Create web2ldapcnf/local.py for AE-DIR
  template:
    src: "{{ aedir_web2ldap_cnf_local }}"
    dest: "{{ web2ldap_cnfdir }}/local.py"
    owner: root
    group: root
    mode: 0644
    validate: "{{ web2ldap_prefix }}/bin/python %s"
  notify:
    - restart web2ldap

- name: Create connect AE-DIR landing page on https://{{ openldap_service_fqdn }}/web2ldap
  template:
    src: "{{ aedir_web2ldap_connect_template }}"
    dest: "{{ web2ldap_templates }}/connect.html"
    owner: root
    group: root
    mode: 0644

- name: web2ldap HTML and LDIF templates for AE-DIR
  template:
    src: "{{ item }}"
    dest: "{{ web2ldap_templates }}/ae-dir/{{ item | basename | regex_replace('\\.j2','') }}"
    owner: root
    group: root
    mode: 0644
  with_fileglob:
    "../templates/web2ldap/*.*.j2"

- name: install AE-DIR plugin module for web2ldap
  copy:
    src: "aedir.py"
    dest: "{{ web2ldap_pylib }}/w2lapp/schema/plugins/aedir.py"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart web2ldap

