---
# Apply AE-DIR configuration to web2ldap

- name: "Set Python {{ aedir_python }} interpreter in web2ldap scripts"
  replace:
    dest: "{{ item }}"
    regexp: '/usr/bin/python2.7 -ROO'
    replace: '{{ aedir_python }}'
    backup: no
  with_items:
  - "{{ web2ldap_sbin_script }}"
  - "{{ web2ldap_fcgi_script }}"
  - "{{ web2ldap_prefix }}/sbin/checkinst.py"

- name: Create web2ldapcnf/local.py for AE-DIR
  template:
    src: "{{ item }}"
    dest: "{{ web2ldap_cnfdir }}/local.py"
    owner: root
    group: root
    mode: 0644
  with_first_found:
    - files:
       - "web2ldap/web2ldapcnf/local.py.j2"
      paths: "{{ aedir_templates_dirs }}"
  notify:
    - restart web2ldap

- name: Create web2ldapcnf/hosts.py for AE-DIR
  template:
    src: "{{ item }}"
    dest: "{{ web2ldap_cnfdir }}/hosts.py"
    owner: root
    group: root
    mode: 0644
  with_first_found:
    - files:
       - "web2ldap/web2ldapcnf/hosts.py.j2"
      paths: "{{ aedir_templates_dirs }}"
  notify:
    - restart web2ldap

- name: "Create connect AE-DIR landing page for web2ldap"
  template:
    src: "{{ item }}"
    dest: "{{ web2ldap_templates }}/connect.html"
    owner: root
    group: root
    mode: 0644
  with_first_found:
    - files:
       - "web2ldap/templates/connect.html.j2"
      paths: "{{ aedir_templates_dirs }}"

- name: "Create search provider file pointing to {{ aedir_main_provider_hostname }}"
  template:
    src: "web2ldap/opensearch-ae-dir.xml.j2"
    dest: "{{ aedir_prefix }}/htdocs/opensearch-ae-dir.xml"
    owner: root
    group: root
    mode: 0644

- name: "web2ldap HTML and LDIF templates for AE-DIR (copy)"
  copy:
    src: "{{ item }}"
    dest: "{{ web2ldap_templates }}/ae-dir/{{ item | basename }}"
    owner: root
    group: root
    mode: 0644
  with_fileglob:
    "web2ldap/templates/ae-dir/*.*"

- name: "web2ldap HTML and LDIF templates for AE-DIR (template)"
  template:
    src: "{{ item }}"
    dest: "{{ web2ldap_templates }}/ae-dir/{{ item | basename | regex_replace('\\.j2','') }}"
    owner: root
    group: root
    mode: 0644
  with_fileglob:
    "../templates/web2ldap/templates/ae-dir/*.*.j2"

- name: install AE-DIR plugin module for web2ldap
  copy:
    src: "web2ldap/aedir.py"
    dest: "{{ web2ldap_pylib }}/w2lapp/schema/plugins/aedir.py"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart web2ldap

- name: Create supplemental schema file for AE-DIR (ae-suppl-schema.ldif)
  copy:
    src: "web2ldap/ae-suppl-schema.ldif"
    dest: "{{ web2ldap_etc }}/ae-suppl-schema.ldif"
    owner: root
    group: root
    mode: 0644
