---
# Apply AE-DIR configuration to OpenLDAP's slapd
#-----------------------------------------------------------------------

- name: Delete the dynamic configuration directory
  file:
    path: "{{ openldap_conf_prefix }}/slapd.d"
    state: absent

# database directory structure
#-----------------------------------------------------------------------

- name: Create OpenLDAP database root directory
  file:
    path: "{{ openldap_data }}"
    state: directory
    owner: ldap
    group: ldap
    mode: 0750

- name: Create database directories
  file:
    path: "{{ openldap_data }}/{{ item }}"
    state: directory
    owner: ldap
    group: ldap
    mode: 0750
  with_items:
    - accesslog
    - um
  notify:
  - restart slapd

# slapd.conf and schema files
#-----------------------------------------------------------------------

- name: Install various OpenLDAP schema files
  copy:
    src: "schema/{{ item }}"
    dest: "{{ openldap_schema_prefix }}/{{ item }}"
    owner: root
    group: ldap
    mode: 0644
  with_items: "{{ openldap_schema_files }}"
  notify:
  - restart slapd

- name: Create central schema including file from template
  template:
    src: "init.schema.j2"
    dest: "{{ openldap_schema_prefix }}/init.schema"
    owner: root
    group: ldap
    mode: 0644
  notify:
  - restart slapd

- name: "Create rootDSE.ldif"
  template:
    src: "rootDSE.ldif.j2"
    dest: "{{ openldap_conf_prefix }}/rootDSE.ldif"
    owner: root
    group: ldap
    mode: 0644

- name: "Create slapd.conf based on role-specific template slapd-{{ openldap_role }}.conf.j2"
  template:
    src: "slapd-{{ openldap_role }}.conf.j2"
    dest: "{{ openldap_conf_file }}"
    owner: root
    group: ldap
    mode: 0640
#    validate: "{{ openldap_sbin }}/slaptest -f %s"
  notify:
  - restart slapd

- name: "Create client config file {{ openldap_conf_prefix }}/ldap.conf from template"
  template:
    src: "ldap.conf.j2"
    dest: "{{ openldap_conf_prefix }}/ldap.conf"
    owner: root
    group: root
    mode: 0644
  notify:
  - restart slapd

- name: Backup slapd databases in CRON job
  cron:
    name: "ae_dir_slapcat"
    state: present
    user: root
    cron_file: ae_dir_slapcat
    minute: "23"
    hour: "*/12"
    job: "{{ openldap_backup_script }}"
  when: openldap_role == 'provider'

# service defaults and service
#-----------------------------------------------------------------------

- name: ensure slapd is running (and enable it at boot)
  service: name=slapd state=started enabled=yes
