---
# configuration for web server apache2

- name: "Create config for Apache from template"
  template:
    src: 'apache2.conf.j2'
    dest: "{{ apache2_config[lsb_id].conf_pathname }}"
    owner: root
    group: root
    mode: 0644
  notify:
    - "restart web server"

- name: "Install apache2 CA cert bundle {{ apache_cacert_filename }} to {{ apache_cacert_pathname }}"
  copy:
    src: "{{ apache_cacert_filename }}"
    dest: "{{ apache_cacert_pathname }}"
    owner: root
    group: root
    mode: 0644
  when: apache_cacert_filename != openldap_cacert_filename and apache_cacert_pathname != openldap_cacert_pathname
  notify:
  - "restart web server"

- name: "Install apache2 server cert {{ apache_cert_filename }} to {{ apache_cert_pathname }}"
  copy:
    src: "{{ apache_cert_filename }}"
    dest: "{{ apache_cert_pathname }}"
    owner: root
    group: root
    mode: 0644
  when: apache_cert_filename != openldap_cert_filename and apache_cert_pathname != openldap_cert_pathname
  notify:
  - "restart web server"

- name: "Install apache2 server key {{ apache_key_filename }} to {{ apache_key_pathname }}"
  copy:
    src: "{{ apache_key_filename }}"
    dest: "{{ apache_key_pathname }}"
    owner: root
    group: root
    mode: 0644
  when: apache_key_filename and (apache_key_filename != openldap_key_filename and apache_key_pathname != openldap_key_pathname)
  no_log: True
  notify:
  - "restart web server"

- name: "Set ownership/permissions of apache2 server key {{ apache_key_pathname }}"
  file:
    path: "{{ apache_key_pathname }}"
    owner: root
    group: root
    mode: 0640
  when: apache_key_pathname != openldap_key_pathname
  notify:
  - "restart web server"
