---
# configuration for web server apache2

- name: "Ensure {{ apache2_config.service_name }} is stopped"
  service:
    name: "{{ apache2_config.service_name }}"
    state: stopped
    enabled: no

- name: "Create ae-apache log directory {{ apache_access_log|dirname }}"
  file:
    path: "{{ apache_access_log|dirname }}"
    state: directory
    owner: "{{ apache_user }}"
    group: root
    mode: 0750
  notify:
    - "restart ae-apache"

- name: "Fix ownership/permissions of Apache log file {{ apache_access_log }}"
  file:
    path: "{{ apache_access_log }}"
    owner: "{{ apache_user }}"
    group: "{{ apache_group }}"
    mode: 0640
  ignore_errors: yes
  notify:
    - "restart ae-apache"

- name: "Create config for Apache from template"
  template:
    src: 'apache2.conf.j2'
    dest: "{{ apache_conf }}"
    owner: root
    group: root
    mode: 0644
  notify:
    - "restart ae-apache"

- name: "Create ae-apache logrotate config"
  template:
    src: "logrotate_ae-apache.j2"
    dest: "/etc/logrotate.d/ae-apache"
    owner: root
    group: root
    mode: 0644

- name: "Create Apache run directory {{ apache_rundir }}"
  file:
    path: "{{ apache_rundir }}"
    state: directory
    owner: root
    group: "{{ apache_group }}"
    mode: 0775
  notify:
    - "restart ae-apache"

- name: "Install apache2 CA cert bundle {{ apache_cacert_filename }} to {{ apache_cacert_pathname }}"
  copy:
    src: "{{ apache_cacert_filename }}"
    dest: "{{ apache_cacert_pathname }}"
    owner: root
    group: root
    mode: 0644
  when: apache_cacert_filename != openldap_cacert_filename and apache_cacert_pathname != openldap_cacert_pathname
  notify:
    - "restart ae-apache"

- name: "Install apache2 server cert {{ apache_cert_filename }} to {{ apache_cert_pathname }}"
  copy:
    src: "{{ apache_cert_filename }}"
    dest: "{{ apache_cert_pathname }}"
    owner: root
    group: root
    mode: 0644
  when: apache_cert_filename != openldap_cert_filename and apache_cert_pathname != openldap_cert_pathname
  notify:
    - "restart ae-apache"

- name: "Install apache2 server key {{ apache_key_filename }} to {{ apache_key_pathname }}"
  copy:
    src: "{{ apache_key_filename }}"
    dest: "{{ apache_key_pathname }}"
    owner: root
    group: "{{ apache_group }}"
    mode: 0640
  when: apache_key_filename and (apache_key_filename != openldap_key_filename and apache_key_pathname != openldap_key_pathname)
  no_log: True
  notify:
    - "restart ae-apache"

- name: "Set ownership/permissions of apache2 server key {{ apache_key_pathname }}"
  file:
    path: "{{ apache_key_pathname }}"
    owner: root
    group: "{{ apache_group }}"
    mode: 0640
  when: apache_key_pathname != openldap_key_pathname
  notify:
    - "restart ae-apache"

- name: "Grant {{ apache_user }} read access to {{ openldap_key_filename }}"
  acl:
    state: present
    path: "{{ openldap_key_pathname }}"
    entity: "{{ apache_user }}"
    etype: user
    permissions: r
  when: apache_key_pathname == openldap_key_pathname
  notify:
    - "restart ae-apache"

- name: "Install systemd unit file for ae-apache"
  template:
    src: "ae-apache.service.j2"
    dest: "{{ aedir_systemd_dir }}/ae-apache.service"
    owner: root
    group: root
    mode: 0644
  notify:
    - "restart ae-apache"
  when: aedir_service_manager == "systemd"

- name: "Create AppArmor profile for {{ apache2_config.httpd_exec }}"
  template:
    src: "apparmor/ae-apache.j2"
    dest: "{{ apparmor_profiles_dir }}/ae-apache"
    owner: root
    group: root
    mode: 0644
  notify:
    - "restart apparmor"
    - "restart ae-apache"
  when: apparmor_enabled == True
