---
# Apply AE-DIR configuration to web2ldap

- name: Create web2ldapcnf/local.py for AE-DIR
  template:
    src: "web2ldapcnf_local.py.j2"
    dest: "{{ web2ldap_cnfdir }}/local.py"
    owner: root
    group: root
    mode: 0644
#    validate: "PYTHONPATH={{ web2ldap_etc }}:{{ web2ldap_prefix }}/pylib {{ web2ldap_prefix }}/bin/python %s"
  notify:
    - restart web server

- name: Create connect AE-DIR landing page on https://{{ inventory_hostname }}/web2ldap
  template:
    src: "web2ldap_connect.html.j2"
    dest: "{{ web2ldap_templates }}/connect.html"
    owner: root
    group: root
    mode: 0644

- name: install AE-DIR plugin module for web2ldap
  copy:
    src: "aedir.py"
    dest: "{{ web2ldap_pylib }}/w2lapp/schema/plugins/aedir.py"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart web server

#- name: web2ldap templates for AE-DIR
#  template: src="{{ item }}.j2" dest="{{ web2ldap_templates }}/ae-dir/{{ item }}" owner=root group=root mode=0644
#  with_items:
#  -

