---
# Install CRON jobs running only on provider

- name: "Install CRON jobs running as root"
  cron:
    name: "{{ item.key }}"
    state: present
    user: root
    cron_file: "{{ aedir_cron_file }}"
    hour: "{{ item.value['hour']|default('*') }}"
    minute: "{{ item.value.minute }}"
    job: "{{ aedir_python }} -m {{ item.value.pyjob }}"
  with_dict:
    aedir_pproc_update:
      minute: "{{ aedir_cron_minutes.aedir_pproc_update }}"
      pyjob: "aedir_pproc.update {{ aedir_rundir }}/aedir_pproc_update.state"

- name: "Install CRON jobs running as ae-dir-pwd"
  cron:
    name: "{{ item.key }}"
    state: present
    user: ae-dir-pwd
    cron_file: "{{ aedir_cron_file }}"
    hour: "{{ item.value['hour']|default('*') }}"
    minute: "{{ item.value.minute }}"
    job: "{{ aedir_python }} -m {{ item.value.pyjob }}"
  with_dict:
    aedir_pproc_welcome:
      minute: "{{ aedir_cron_minutes.aedir_pproc_welcome }}"
      pyjob: "aedir_pproc.welcome"
    aedir_pwd_expreset:
      minute: "{{ aedir_cron_minutes.aedir_pwd_expreset }}"
      pyjob: "aedir_pproc.pwd.expreset"
    aedir_pwd_expwarn:
      hour: "1"
      minute: "23"
      pyjob: "aedir_pproc.pwd.expwarn"

- name: "Install CRON job for exporting slapd databases"
  cron:
    name: "ae_dir_slapcat"
    state: present
    user: root
    cron_file: "{{ aedir_cron_file }}"
    minute: "{{openldap_backup_cron_args.minute }}"
    hour: "{{openldap_backup_cron_args.hour }}"
    job: "{{ openldap_backup_script }}"
  when: openldap_role == 'provider'
