---
# Install CRON jobs on provider

- name: "Set env vars in {{ aedir_cron_file }}"
  cron:
    env: yes
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    user: root
    cron_file: "{{ aedir_cron_file }}"
  with_dict:
    HOME: "{{ aedir_rundir }}"
    MAILTO: ""
    LD_LIBRARY_PATH: "{{ os_openldap_paths.openldap_libdir }}"
    LDAPRC: "{{ aedir_etc }}/ldap.conf"
    PYTHONPATH: "{{ aedir_etc }}/ae-dir-pwd"
    PYTHONOPTIMIZE: "2"
    PYTHONDONTWRITEBYTECODE: "1"
    PYTHONWARNINGS: "error"
    AE_LOGGER_QUALNAME: "aedir.syslog"

- name: "Install CRON jobs running as root"
  cron:
    name: "{{ item.key }}"
    state: present
    user: root
    cron_file: "{{ aedir_cron_file }}"
    hour: "{{ item.value['hour']|default('*') }}"
    minute: "{{ item.value.minute }}"
    job: "{{ aedir_python }} -m {{ item.value.pyjob }}"
  with_dict:
    aedir_pproc_groups:
      minute: "*/3"
      pyjob: aedir_pproc.groups
    aedir_pproc_status:
      minute: "*/13"
      pyjob: "aedir_pproc.status"
    aedir_pproc_persattrs:
      minute: "*/2"
      pyjob: "aedir_pproc.persattrs {{ aedir_rundir }}/aedir_pproc_persattrs.state"

- name: "Install CRON jobs running as ae-dir-pwd"
  cron:
    name: "{{ item.key }}"
    state: present
    user: ae-dir-pwd
    cron_file: "{{ aedir_cron_file }}"
    hour: "{{ item.value['hour']|default('*') }}"
    minute: "{{ item.value.minute }}"
    job: "{{ aedir_python }} -m {{ item.value.pyjob }}"
  with_dict:
    aedir_pproc_welcome:
      minute: "*/2"
      pyjob: "aedir_pproc.welcome"
    aedir_pwd_expreset:
      minute: "*/2"
      pyjob: "aedir_pproc.pwd.expreset"
    aedir_pwd_expwarn:
      hour: "0"
      minute: "0"
      pyjob: "aedir_pproc.pwd.expwarn"
