---
# Install CRON jobs

- name: "Set env vars in {{ aedir_cron_file }}"
  cron:
    env: yes
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    user: root
    cron_file: "{{ aedir_cron_file }}"
  with_dict:
    HOME: "{{ aedir_rundir }}"
    MAILTO: ""
    LD_LIBRARY_PATH: "{{ openldap_path.libdir }}"
    LDAPRC: "{{ aedir_etc }}/ldap.conf"
    PYTHONPATH: "{{ aedir_etc }}/ae-dir-pwd"
    PYTHONOPTIMIZE: "2"
    PYTHONDONTWRITEBYTECODE: "1"
    PYTHONWARNINGS: "error"
    AE_LOGGER_QUALNAME: "{{ aedir_logging_qualname }}"

- name: "Remove metrics text export CRON job"
  cron:
    name: "slapd_metrics"
    state: absent
    cron_file: "{{ aedir_cron_file }}"
  when: aedir_metricsdir == ""

- name: "Install metrics text export CRON job"
  cron:
    name: "slapd_metrics"
    state: present
    user: root
    cron_file: "{{ aedir_cron_file }}"
    hour: "*"
    minute: "*/2"
    job: "{{ aedir_sbin }}/slapd_metrics.sh > {{ aedir_metricsdir }}/ae-slapd.prom.tmp && mv {{ aedir_metricsdir }}/ae-slapd.prom.tmp {{ aedir_metricsdir }}/ae-slapd.prom"
  when: aedir_metricsdir != ""
