---
# install OpenLDAP packages

- name: "Add LTB OpenLDAP repository key"
  apt_key:
    data: "{{ lookup('file', 'RPM-GPG-KEY-LTB-project') }}"
    state: present

- name: "Add LTB OpenLDAP Debian repository {{ ltb_openldap_repo_source }}"
  apt_repository:
    repo: "{{ ltb_openldap_repo_source }}"
    state: present
    update_cache: yes

- name: "Install LTB OpenLDAP packages and dependencies"
  apt:
    name: "{{ item }}"
    state: installed
    update_cache: yes
    cache_valid_time: 3600
    install_recommends: no
    dpkg_options: 'force-confold,force-confdef'
  notify:
  - restart slapd
  with_items:
  - openldap-ltb
  - openldap-ltb-contrib-overlays
  - openldap-ltb-mdb-utils
  - openldap-ltb-ppm
  - openldap-ltb-check-password
  - cracklib-runtime

- name: "Remove Debian package ldap-utils"
  apt:
    name: ldap-utils
    state: absent
