---
# install OpenLDAP packages

- name: Install OpenLDAP packages and dependencies
  zypper:
    name:
      - cyrus-sasl
      - libldap-2_4-2
      - openldap2
      - openldap2-back-sock
      - openldap2-client
      - openldap2-contrib
      - openldap2-ppolicy-check-password
    state: latest
    disable_recommends: yes
    type: package
  notify:
    - "restart ae-slapd"
