---
# install OpenLDAP packages on CentOS

- name: "Copy GPG key file for LTB OpenLDAP repository"
  copy:
    src: "{{ aedir_pkg_repos['ltb_project_org'].key }}"
    dest: "/etc/pki/rpm-gpg/{{ aedir_pkg_repos['ltb_project_org'].key }}"
    owner: root
    group: root
    mode: 0o0600

- name: "Add LTB OpenLDAP repository"
  yum_repository:
    name: ltp-openldap
    description: LTB OpenLDAP repository
    baseurl: "{{ aedir_pkg_repos['ltb_project_org'].repo }}"
    gpgkey: "file:///etc/pki/rpm-gpg/{{ aedir_pkg_repos['ltb_project_org'].key }}"
    gpgcheck: yes

- name: "Install OpenLDAP packages and dependencies"
  yum:
    name:
      - openldap-ltb
      - openldap-ltb-contrib-overlays
      - openldap-ltb-mdb-utils
      - cracklib
    state: latest
    update_cache: yes
  notify:
    - "restart {{ openldap_service_name }}"
