---
# installing apache2 on Debian

- name: "Install packages needed for running Apache 2.4 on {{ lsb_id }}"
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  notify:
  - "restart web server"
  with_items:
  - httpd
  - mod_fcgid
  - mod_ssl
