---
# install check_mk package and scripts

- name: Install python-ldap and pyasn1 modules
  apt:
    name: "{{ item }}"
    state: installed
    install_recommends: no
    dpkg_options: 'force-confold,force-confdef'
  with_items:
  - python-ldap
  - python-pyasn1
  - python-pyasn1-modules

- name: Install check_mk
  apt: name=check-mk-agent state=installed update_cache=yes install_recommends=no dpkg_options='force-confold,force-confdef'
  when: ansible_os_family == 'Debian'

- name: Install check_mk monitoring Python script
  copy:
    src: "slapd_checkmk.py"
    dest: "/usr/local/sbin/slapd_checkmk.py"
    owner: root
    group: ldap
    mode: 0750

- name: Install check_mk monitoring Python script
  copy:
    src: "slapd_checkmk.sh"
    dest: "/usr/lib/check_mk_agent/local/slapd_checkmk.sh"
    owner: root
    group: ldap
    mode: 0750

