---
# install OpenLDAP packages on RHEL-alike

- name: "Copy GPG key file for LTB OpenLDAP repository"
  copy:
    src: "{{ aedir_pkg_repos['sofl'].key }}"
    dest: "/etc/pki/rpm-gpg/{{ aedir_pkg_repos['sofl'].key }}"
    owner: root
    group: root
    mode: 0o0600

- name: "Add Symas OpenLDAP for Linux repository"
  yum_repository:
    name: sofl
    description: "Symas OpenLDAP for Linux RPM repository"
    baseurl: "{{ aedir_pkg_repos['sofl'].repo }}"
    gpgkey: "file:///etc/pki/rpm-gpg/{{ aedir_pkg_repos['sofl'].key }}"
    gpgcheck: yes

- name: "Install Symas OpenLDAP for Linux packages"
  yum:
    name:
      - symas-openldap-libs
      - symas-openldap-devel
      - symas-openldap-clients
      - symas-openldap-servers
    state: latest
    update_cache: yes
  notify:
    - "restart {{ openldap_service_name }}"
