---
# installing apache2 on Debian

- name: "Install packages needed for running Apache 2.4"
  apt:
    name:
      - apache2
    state: present
    update_cache: no
    install_recommends: no
    dpkg_options: 'force-confold,force-confdef'
  notify:
    - "restart ae-apache"
