---
# installing apache2 on Debian

- name: "Install packages needed for running Apache 2.4 on {{ lsb_id }}"
  yum:
    name:
      - httpd
      - mod_ssl
      - mod_proxy_uwsgi
    state: present
    update_cache: yes
  notify:
    - "restart ae-apache"

- name: "Install UWSGI packages on {{ lsb_id }}"
  yum:
    name:
      - uwsgi
      - uwsgi-plugin-python2
    state: present
    update_cache: yes
  notify:
    - "restart aedirpwd"
    - "restart oathenroll"
    - "restart web2ldap"
