---
# install OpenLDAP packages in openSUSE/SLE

- name: "Install OpenLDAP dependencies"
  zypper:
    name:
      - "libsasl2-3"
      - "cyrus-sasl"
    state: latest
    disable_recommends: yes
    type: package
  notify:
    - "restart {{ openldap_service_name }}"

- name: "Install LMDB tools"
  zypper:
    name:
      - "lmdb"
    state: latest
    disable_recommends: yes
    extra_args: "--allow-vendor-change"
    type: package

- name: "Install OpenLDAP packages"
  zypper:
    name:
      - "openldap2"
      - "openldap2-back-sock"
      - "openldap2-client"
      - "openldap2-contrib"
    state: latest
    disable_recommends: yes
    extra_args: "--allow-vendor-change"
    type: package
  notify:
    - "restart {{ openldap_service_name }}"
