---
# install OpenLDAP packages

- name: "Add AE-DIR repository key"
  apt_key:
    data: "{{ lookup('file', item.value.key) }}"
    state: present
  with_dict: "{{ aedir_pkg_repos }}"

- name: "Add AE-DIR Debian repository"
  apt_repository:
    filename: "{{ item.key }}"
    repo: "{{ item.value.repo }}"
    state: present
    update_cache: yes
  with_dict: "{{ aedir_pkg_repos }}"

- name: "Install AE-DIR OpenLDAP packages and dependencies"
  apt:
    name:
      - libsodium23
      - openldap-ms
      - openldap-ms-contrib-overlays
      - openldap-ms-mdb-utils
    state: latest
    update_cache: no
    install_recommends: no
    dpkg_options: 'force-confold,force-confdef'
  notify:
    - "restart {{ openldap_service_name }}"
