---
# install OpenLDAP packages

- name: Install OpenLDAP packages and dependencies
  zypper:
    name: "{{ item }}"
    state: latest
    disable_recommends: yes
    type: package
  notify:
    - restart slapd
  with_items:
    - cyrus-sasl
    - openldap2
    - openldap2-back-sock
    - openldap2-client
    - openldap2-contrib
    - openldap2-ppolicy-check-password

