---
# install OpenLDAP packages

- name: copy GPG key file
  copy:
    src: RPM-GPG-KEY-LTB-project
    dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-LTB-project
    owner: root
    group: root
    mode: 0600

- name: "Add LTB OpenLDAP repository"
  yum_repository:
    name: ltp-openldap
    description: LTB OpenLDAP repository
    baseurl: "{{ ltb_openldap_repo_source }}"
    gpgkey: "file:///etc/pki/rpm-gpg/RPM-GPG-KEY-LTB-project"
    gpgcheck: yes

- name: Install OpenLDAP packages and dependencies
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  notify:
    - restart slapd
  with_items:
    - openldap-ltb
    - openldap-ltb-contrib-overlays
    - openldap-ltb-mdb-utils
    - openldap-ltb-ppm
    - openldap-ltb-check-password
    - cracklib

- name: "Fix ownership of LTB directory"
  file:
    path: /usr/local/openldap
    owner: root
    group: root

- name: "Fix ownership in LTB sub-directories"
  file:
    path: "{{ item }}"
    owner: root
    group: root
    recurse: yes
  with_items:
    - /usr/local/openldap/bin
    - /usr/local/openldap/etc
    - /usr/local/openldap/include
    - /usr/local/openldap/lib64
    - /usr/local/openldap/libexec
    - /usr/local/openldap/sbin
    - /usr/local/openldap/share
