---
# install OpenLDAP packages

- name: "Add LTB OpenLDAP repository key"
  apt_key:
    data: "{{ lookup('file', 'RPM-GPG-KEY-LTB-project') }}"
    state: present

- name: "Add LTB OpenLDAP Debian repository {{ ltb_openldap_repo_source }}"
  apt_repository:
    repo: "{{ ltb_openldap_repo_source }}"
    state: present
    update_cache: yes

- name: "Overwrite LTB package init script"
  template:
    src: "init_slapd_exit0.j2"
    dest: "/etc/init.d/slapd"
    owner: root
    group: root
    mode: 0755

- name: "Install LTB OpenLDAP packages and dependencies"
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
    cache_valid_time: 3600
    install_recommends: no
    dpkg_options: 'force-confold,force-confdef'
  notify:
  - restart slapd
  with_items:
  - openldap-ltb
  - openldap-ltb-contrib-overlays
  - openldap-ltb-mdb-utils
  - openldap-ltb-ppm
  - openldap-ltb-check-password
  - cracklib-runtime

- name: "Remove Debian package ldap-utils"
  apt:
    name: ldap-utils
    state: absent

- name: "Fix ownership of LTB directory"
  file:
    path: /usr/local/openldap
    owner: root
    group: root

- name: "Fix ownership in LTB sub-directories"
  file:
    path: "{{ item }}"
    owner: root
    group: root
    recurse: yes
  with_items:
    - /usr/local/openldap/bin
    - /usr/local/openldap/etc
    - /usr/local/openldap/include
    - /usr/local/openldap/lib64
    - /usr/local/openldap/libexec
    - /usr/local/openldap/sbin
    - /usr/local/openldap/share
