---
# installing apache2 on openSUSE/SLE

- name: "Install packages needed for running Apache 2.4"
  zypper:
    name:
      - apache2
      - "apache2-{{ apache2_mpm_model }}"
    state: present
    disable_recommends: yes
    type: package
  notify:
    - "restart ae-apache"
