---
# installing apache2 on RHEL-alike

- name: "Install packages needed for running Apache 2.4 on {{ lsb_id }}"
  yum:
    name:
      - httpd
      - mod_ssl
    state: present
    update_cache: no
  notify:
    - "restart ae-apache"
