---
# install OpenLDAP packages on Ubuntu

- name: create /etc/sasl2
  file:
    path: /etc/sasl2
    state: directory

- name: "Add AE-DIR repository key"
  apt_key:
    data: "{{ lookup('file', item.value.key) }}"
    state: present
  with_dict: "{{ aedir_pkg_repos }}"

- name: "Remove old AE-DIR APT repository"
  apt_repository:
    state: absent
    filename: "AE-DIR"
    repo: "deb https://ae-dir.com/repo/debian/ buster main"

- name: "Add AE-DIR APT repository"
  apt_repository:
    state: present
    filename: "{{ item.key }}"
    repo: "{{ item.value.repo }}"
    update_cache: yes
    validate_certs: yes
  with_dict: "{{ aedir_pkg_repos }}"

- name: "Install AE-DIR OpenLDAP packages and dependencies"
  apt:
    name:
      - openldap-ms
      - openldap-ms-contrib-overlays
      - openldap-ms-mdb-utils
    state: latest
    update_cache: no
    install_recommends: no
    dpkg_options: 'force-confold,force-confdef'
  notify:
    - "restart {{ openldap_service_name }}"
