---
# install OpenLDAP packages

- name: "Add LTB OpenLDAP repository key"
  apt_key:
    data: "{{ lookup('file', aedir_pkg_repos['ltb_project_org'].key) }}"
    state: present

- name: "Add LTB Debian repository"
  apt_repository:
    filename: "ltb_project_org"
    repo: "{{ aedir_pkg_repos['ltb_project_org'].repo }}"
    state: present
    update_cache: yes

- name: "Install LTB OpenLDAP packages and dependencies"
  apt:
    name:
      - openldap-ltb
      - openldap-ltb-contrib-overlays
      - openldap-ltb-mdb-utils
      - cracklib-runtime
    state: latest
    update_cache: no
    install_recommends: no
    dpkg_options: 'force-confold,force-confdef'
  notify:
    - "restart {{ openldap_service_name }}"

- name: "Fix ownership of LTB directory"
  file:
    path: /usr/local/openldap
    owner: root
    group: root

- name: "Fix ownership in LTB sub-directories"
  file:
    path: "{{ item }}"
    owner: root
    group: root
    recurse: yes
  with_items:
    - /usr/local/openldap/bin
    - /usr/local/openldap/etc
    - /usr/local/openldap/include
    - /usr/local/openldap/lib64
    - /usr/local/openldap/libexec
    - /usr/local/openldap/sbin
    - /usr/local/openldap/share
