---
# installing apache2 on Debian

- name: "Install packages needed for running Apache 2.4 on {{ lsb_id }}"
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  notify:
    - "restart web server"
  with_items:
    - httpd
    - mod_ssl
    - mod_proxy_uwsgi

- name: "Install UWSGI packages on {{ lsb_id }}"
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  notify:
    - "restart aedirpwd"
    - "restart oathenroll"
    - "restart web2ldap"
  with_items:
    - uwsgi
    - uwsgi-plugin-python
