---
# installing apache2 on Debian

- name: "Install packages needed for running Apache 2.4 on {{ lsb_id }}"
  apt:
    name:
      - apache2
      - libapache2-mod-proxy-uwsgi
    state: present
    update_cache: yes
    cache_valid_time: 3600
    install_recommends: no
    dpkg_options: 'force-confold,force-confdef'
  notify:
    - "restart ae-apache"

- name: "Install UWSGI packages on {{ lsb_id }}"
  apt:
    name:
      - uwsgi
      - uwsgi-plugin-python
    state: present
    update_cache: yes
    cache_valid_time: 3600
    install_recommends: no
    dpkg_options: 'force-confold,force-confdef'
  notify:
    - "restart aedirpwd"
    - "restart oathenroll"
    - "restart web2ldap"
