---
# install OpenLDAP packages

- name: Install OpenLDAP packages and dependencies
  zypper:
    name: "{{ item }}"
    state: present
    disable_recommends: yes
    type: package
  notify:
    - restart slapd
  with_items:
    - cyrus-sasl
    - openldap2
    - openldap2-back-sock
    - openldap2-client
    - openldap2-contrib
    - openldap2-ppolicy-check-password

- name: Create /etc/sysconfig/openldap
  template:
    src: "{{ lsb_id }}/sysconfig_openldap.j2"
    dest: "/etc/sysconfig/openldap"
    owner: root
    group: root
    mode: 0644
  notify:
  - restart slapd
