---
# install OpenLDAP packages on Debian

- name: "Set custom AE-DIR APT repository"
  ansible.builtin.copy:
    content: "{{ item.value.repo }}"
    dest: "/etc/apt/sources.list.d/{{ item.key }}.list"
    owner: "root"
    group: "root"
    mode: 0o644
  register: aedir_apt_repo
  with_dict: "{{ aedir_pkg_repos }}"

- name: "Refresh AE-DIR APT repository"
  apt_repository:
    state: present
    filename: "{{ item.key }}"
    repo: "{{ item.value.repo }}"
    update_cache: yes
    validate_certs: yes
  with_dict: "{{ aedir_pkg_repos }}"
  when: aedir_apt_repo.changed

- name: "Install AE-DIR OpenLDAP packages and dependencies"
  apt:
    name:
      - openldap-ms
      - openldap-ms-contrib-overlays
      - openldap-ms-mdb-utils
    state: latest
    update_cache: no
    install_recommends: no
    dpkg_options: 'force-confold,force-confdef'
  notify:
    - "restart {{ openldap_service_name }}"
