---
# tasks file for roles/ae-dir-server

# get root user info
- getent:
    database: passwd
    key: aehostd
  ignore_errors: yes
  tags:
    - always

- debug:
    var: "{{ item }}"
    verbosity: 1
  with_items:
    - lsb_id
    - inventory_dir
    - playbook_dir
    - role_path
    - aedir_files_dirs
    - aedir_templates_dirs
    - aedir_providers_restrictions
    - aedir_replicas_restrictions
    - getent_passwd.aehostd
  tags:
    - always

- name: "Forced stop of all services"
  service:
    name: "{{ item }}"
    state: stopped
  ignore_errors: yes
  when: aedir_stop is defined
  with_items:
    - ae-dir-pwd
    - "{{ openldap_service_name }}"
    - ae-apache
    - "{{ oath_bind_listener }}"
    - oathenroll
    - web2ldap

- name: "Include OS-specific variables"
  include_vars:
    file: "{{ lsb_id }}.yml"
  tags:
    - always

- debug:
    var: "{{ item }}"
    verbosity: 1
  with_items:
    - aedir_python
    - aedir_cron_file
  tags:
    - always

- name: "Store Python interpreter used for ansible modules as host fact"
  set_fact:
    cacheable: yes
    aedir_python3: "{{ aedir_python }}"
  tags:
    - always

- name: "OS base configuration"
  include_tasks: "baseos_{{ lsb_id }}.yml"

- block:
    - name: "Install AppArmor packages"
      include_tasks: "apparmor.yml"
      when: apparmor_enabled == True
  tags:
    - aedir_apparmor

- name: "Install OpenLDAP packages"
  include_tasks: "install_openldap_{{ lsb_id }}.yml"

- name: "Install apache2 on {{ lsb_id }}"
  include_tasks: "install_apache2_{{ lsb_id }}.yml"
  when: openldap_role == 'provider'

- block:
    - name: "Check for old Python 2 virtualenv in {{ aedir_prefix }}"
      stat:
        path: "{{ aedir_bin }}/python2"
      register: py2_venv

    - name: "Remove old Python 2 virtualenv"
      file:
        path: "{{ item }}"
        state: absent
      ignore_errors: yes
      with_items:
        - "{{ aedir_bin }}"
        - "{{ aedir_prefix }}/include"
        - "{{ aedir_prefix }}/lib"
        - "{{ aedir_prefix }}/lib64"
        - "{{ aedir_prefix }}/pip-selfcheck.json"
      when: py2_venv.stat.exists

    - name: "Create directory structure {{ aedir_prefix }}"
      file:
        path: "{{ item }}"
        state: directory
        owner: root
        group: root
        mode: u=rwx,g=rx,o=rx
      with_items:
        - "{{ aedir_etc }}"
        - "{{ aedir_etc }}/uwsgi"
        - "{{ aedir_bin }}"
        - "{{ aedir_sbin }}"
        - "{{ aedir_rundir }}"
        - "{{ aedir_rundir }}/uwsgi"
  tags:
    - aedir_tools

- block:
    - name: "Add system accounts on {{ openldap_role }}"
      include_tasks: system_accounts.yml
  tags:
    - aedir_tools

- block:
    - name: "Configure OpenLDAP slapd for AE-DIR"
      include_tasks: configure_slapd.yml
  tags:
    - aedir_slapd

- block:
    - name: "Install various AE-DIR tools"
      include_tasks: aedir_tools.yml
  tags:
    - aedir_tools

- block:
    - name: "TLS configuration for OpenLDAP slapd"
      include_tasks: tls_files.yml
  tags:
    - openldap_tls_files

- block:
    - name: "Specific AE-DIR tool tasks on {{ lsb_id }}"
      include_tasks: "aedir_tools_{{ lsb_id }}.yml"
  tags:
    - aedir_tools

- block:
    - name: "Specific AE-DIR tool tasks on {{ openldap_role }}"
      include_tasks: "aedir_tools_{{ openldap_role }}.yml"
  tags:
    - aedir_tools

- block:
    - name: "AE-DIR web pages {{ openldap_role }}"
      include_role:
        name: aedir_htdocs
      vars:
        document_root: "{{ aedir_htdocsdir }}"
        htdocs_templates: "{{ aedir_htdocs_templates }}"
        htdocs_layout: "{{ aedir_htdocs_layout }}"
        news: "{{ aedir_news }}"
      when: openldap_role=="provider"
  tags:
    - aedir_htdocs

- block:
    - name: "Configure apache2"
      include_tasks: "configure_apache2.yml"
      when: openldap_role == 'provider'
  tags:
    - aedir_httpd

- block:
    - name: "Install AE-DIR password service (ae-dir-pwd)"
      include_tasks: "pwd.yml"
      when: openldap_role=="provider"
  tags:
    - aedir_pwd

- block:
    - name: "Install and configure web2ldap on {{ openldap_role }}"
      include_tasks: "web2ldap.yml"
      when: openldap_role=="provider"
  tags:
    - aedir_web2ldap

- block:
    - name: "OATH-LDAP tasks on {{ openldap_role }}"
      include_tasks: "oath_ldap.yml"
      when: oath_ldap_enabled == True
  tags:
    - aedir_oath

- block:
    - name: "OATH-LDAP enrollment web app on {{ openldap_role }}"
      include_tasks: "oathenroll.yml"
      when: oath_ldap_enabled == True and openldap_role=="provider"
  tags:
    - aedir_oath
    - aedir_oathenroll

- block:
    - name: "Password sync tasks on {{ openldap_role }}"
      include_tasks: "pwsync.yml"
      when: openldap_role=="provider" and aedir_pwsync_targeturl
  tags:
    - aedir_pwsync

- block:
    - name: "Monitoring scripts on {{ openldap_role }}"
      include_tasks: "monitoring.yml"
  tags:
    - aedir_monitoring

- block:
    - name: "Install CRON jobs on {{ openldap_role }}"
      include_tasks: "cron.yml"
  tags:
    - aedir_cron

- block:
    - name: "Services on {{ openldap_role }}"
      include_tasks: "services.yml"
  tags:
    - aedir_services

- block:

  - name: "Tasks for loading initial data"
    include_tasks: "aedir_init.yml"
    when: aedir_init is defined and openldap_role == "provider"

  - name: "Init aeHost entry on {{ aedir_main_provider_hostname }}"
    aehost:
      name: "{{ inventory_hostname }}"
      state: "{{ aedir_aehost_state }}"
      srvgroup: "{{ aedir_srvgroup }}"
      description: "AE-DIR {{ openldap_role }} host {{ openldap_service_fqdn }}"
      ticket_id: "{{ aedir_init_ticket_id }}"
      ppolicy: "cn=ppolicy-systems,cn=ae,{{ aedir_suffix }}"
      askotp: "no"
    vars:
      ansible_python_interpreter: "{{ hostvars[aedir_main_provider_hostname].aedir_python3 }}"
    delegate_to: "{{ aedir_main_provider_hostname }}"
    become: no
    register: aehost_result

  - name: "Update aeService entries for local system accounts via {{ aedir_main_provider_hostname }}"
    aeservice:
      name: "{{ item.value.cn }}"
      state: "present"
      object_classes:
        - account
        - aeObject
        - aeService
        - posixAccount
      uid: "{{ item.key }}"
      description: "{{ item.value.description }}"
      zone: "ae"
      uid_number: "{{ item.value.uid_number|int }}"
      gid_number: "{{ item.value.gid_number|int }}"
      ppolicy: "cn=ppolicy-sasl-external,cn=ae,{{ aedir_suffix }}"
      login_shell: "{{ aedir_nologin_shell }}"
      home_directory: "{{ aedir_rundir+'/'+item.key }}"
      ticket_id: "{{ aedir_init_ticket_id }}"
      groups: "{{ item.value.get('groups', []) }}"
    with_dict:
      "{{ aedir_ldapi_services }}"
    vars:
      ansible_python_interpreter: "{{ hostvars[aedir_main_provider_hostname].aedir_python3 }}"
    run_once: yes
    delegate_to: "{{ aedir_main_provider_hostname }}"
    become: no

  - name: "Init aeService entry via {{ aedir_main_provider_hostname }}"
    aeservice:
      name: "ae-dir-slapd_{{ openldap_service_fqdn }}"
      state: "present"
      object_classes:
        - account
        - aeObject
        - aeService
        - posixAccount
      host: "{{ inventory_hostname }}"
      zone: "ae"
      description: "AE-DIR slapd {{ openldap_role }} {{ openldap_service_fqdn }} running on {{ inventory_hostname }}"
      ticket_id: "{{ aedir_init_ticket_id }}"
      ppolicy: "cn=ppolicy-sasl-external,cn=ae,{{ aedir_suffix }}"
      see_also: "{{ hostvars[inventory_hostname].openldap_cert_subject }}"
      login_shell: "{{ aedir_nologin_shell }}"
      groups:
        - "ae-replicas"
        - "{{ 'ae-providers' if openldap_role == 'provider' else None }}"
    vars:
      ansible_python_interpreter: "{{ hostvars[aedir_main_provider_hostname].aedir_python3 }}"
    delegate_to: "{{ aedir_main_provider_hostname }}"
    become: no
    register: aeservice_result
    notify:
      - "restart {{ openldap_service_name }}"

  - name: "Wait for replication of changes"
    pause:
      seconds: 5
    when: aehost_result.changed or aeservice_result.changed

  - block:

    - name: "Init aehostd with a SSH ping"
      connection: "ssh"
      remote_user: "aehost-init"
      vars:
        ansible_password: "{{ aehost_result.password }}"
        ansible_ssh_args: "-o PasswordAuthentication=yes -o RequestTTY=no -o PreferredAuthentications=password"
      ping:
        data: "pong"
      become: no
      ignore_unreachable: yes

    - name: "Wait aehostd refresh"
      pause:
        seconds: 6

    - name: "Normal SSH ping"
      ping:
        data: "pong"
      become: no

    when: aehost_result.changed and aehost_result.password

  tags:
    - aedir_init
