---
# tasks file for roles/ae-dir-server

- debug:
    var: "{{ item }}"
    verbosity: 1
  with_items:
    - inventory_dir
    - playbook_dir
    - role_path
    - aedir_templates_dirs
    - aedir_files_dirs
  tags:
    - always

- name: "Include OS-specific variables"
  include_vars: "{{ lsb_id }}.yml"
  tags:
    - always

- name: "OS base configuration"
  include_tasks: "baseos_{{ lsb_id }}.yml"

- block:
    - name: "Install AppArmor packages"
      include_tasks: "apparmor.yml"
      when: apparmor_enabled == True
  tags:
    - apparmor

- name: "Install OpenLDAP packages"
  include_tasks: "install_openldap_{{ lsb_id }}.yml"

- name: "Install apache2 on {{ lsb_id }}"
  include_tasks: "install_apache2_{{ lsb_id }}.yml"
  when: openldap_role == 'provider'

- block:
    - name: "Create directory structure {{ aedir_prefix }}"
      file:
        path: "{{ item }}"
        state: directory
        owner: root
        group: root
        mode: u=rwx,g=rx,o=rx
      with_items:
        - "{{ aedir_etc }}"
        - "{{ aedir_etc }}/uwsgi"
        - "{{ aedir_bin }}"
        - "{{ aedir_sbin }}"
        - "{{ aedir_rundir }}"
        - "{{ aedir_rundir }}/uwsgi"
  tags:
    - aedir_tools

- block:
    - name: "Add system accounts on {{ openldap_role }}"
      include_tasks: system_accounts.yml
  tags:
    - aedir_tools

- block:
    - name: "Configure OpenLDAP slapd for AE-DIR"
      include_tasks: configure_slapd.yml
  tags:
     - slapd_conf

- block:
    - name: "Install various AE-DIR tools"
      include_tasks: aedir_tools.yml
  tags:
    - aedir_tools

- block:
    - name: "TLS configuration for OpenLDAP slapd"
      include_tasks: tls_files.yml
  tags:
    - openldap_tls_files

- block:
    - name: "Specific AE-DIR tool tasks on {{ lsb_id }}"
      include_tasks: "aedir_tools_{{ lsb_id }}.yml"
  tags:
    - aedir_tools

- block:
    - name: "Specific AE-DIR tool tasks on {{ openldap_role }}"
      include_tasks: "aedir_tools_{{ openldap_role }}.yml"
  tags:
    - aedir_tools

- block:
    - name: "AE-DIR web pages {{ openldap_role }}"
      include_role:
        name: ae-dir-htdocs
      vars:
        document_root: "{{ aedir_htdocsdir }}"
        htdocs_templates: "{{ aedir_htdocs_templates }}"
        htdocs_layout: "{{ aedir_htdocs_layout }}"
        news: "{{ aedir_news }}"
      when: openldap_role=="provider"
  tags:
    - htdocs

- block:
    - name: "Configure apache2"
      include_tasks: "configure_apache2.yml"
      when: openldap_role == 'provider'
  tags:
     - apache_conf

- block:
    - name: "Install AE-DIR password service (ae-dir-pwd)"
      include_tasks: "pwd.yml"
      when: openldap_role=="provider"
  tags:
    - pwd

- block:
    - name: "Install and configure web2ldap on {{ openldap_role }}"
      include_tasks: "web2ldap.yml"
      when: openldap_role=="provider"
  tags:
    - web2ldap

- block:
    - name: "OATH-LDAP tasks on {{ openldap_role }}"
      include_tasks: "oath-ldap.yml"
      when: oath_ldap_enabled == True
  tags:
    - oath

- block:
    - name: "OATH-LDAP enrollment web app on {{ openldap_role }}"
      include_tasks: "oathenroll.yml"
      when: oath_ldap_enabled == True and openldap_role=="provider"
  tags:
     - oath
     - oathenroll

- block:
    - name: "Password sync tasks on {{ openldap_role }}"
      include_tasks: "pwsync.yml"
      when: openldap_role=="provider" and aedir_pwsync_targeturl
  tags:
    - pwsync

- block:
    - name: "Monitoring scripts on {{ openldap_role }}"
      include_tasks: "slapd_monitoring.yml"
  tags:
    - monitoring

- block:
    - name: "Install CRON jobs on {{ openldap_role }}"
      include_tasks: "cron.yml"
      when: openldap_role=="provider"
  tags:
    - cron

- block:
    - name: "Services on {{ openldap_role }}"
      include_tasks: "services.yml"
  tags:
    - services
