---
# tasks file for roles/ae-dir-server

- debug:
    var: "{{ item }}"
    verbosity: 1
  with_items:
    - inventory_dir
    - playbook_dir
    - role_path
    - aedir_templates_dirs
    - aedir_files_dirs

- name: "OS base configuration"
  include: "baseos_{{ lsb_id }}.yml"

- name: "Install OpenLDAP packages"
  include: "install_openldap_{{ lsb_id }}.yml"

- name: "Install apache2 on {{ lsb_id }}"
  include: "install_apache2_{{ lsb_id }}.yml"
  when: openldap_role == 'provider'

- name: "Configure OpenLDAP slapd for AE-DIR"
  include: configure_slapd.yml
  tags:
     - slapd_conf

- name: "Add system accounts on {{ openldap_role }}"
  include: system_accounts.yml
  when: openldap_role == 'provider'

- name: "Install various AE-DIR tools"
  include: aedir_tools.yml
  tags:
    - aedir_tools

- name: "TLS configuration for OpenLDAP slapd"
  include: tls_files.yml
  tags:
    - openldap_tls_files

- name: "Specific AE-DIR tool tasks on {{ lsb_id }}"
  include: "aedir_tools_{{ lsb_id }}.yml"
  tags:
    - aedir_tools

- name: "Specific AE-DIR tool tasks on {{ openldap_role }}"
  include: "aedir_tools_{{ openldap_role }}.yml"

- name: "Install web2ldap on {{ openldap_role }}"
  include: "web2ldap.yml"
  when: openldap_role=="provider"

- name: "Configure apache2"
  include: "configure_apache2.yml"
  when: openldap_role == 'provider'
  tags:
     - apache_conf

- name: "Install AE-DIR password service (aedirpwd)"
  include: "aedirpwd.yml"
  when: openldap_role=="provider"
  tags:
    - aedirpwd

- name: "Customize web2ldap for AE-DIR on {{ openldap_role }}"
  include: configure_web2ldap.yml
  when: openldap_role=="provider"

- name: "OATH-LDAP tasks on {{ openldap_role }}"
  include: "oath-ldap.yml"
  when: oath_ldap_enabled == True
  tags:
    - oath

- name: "Monitoring scripts on {{ openldap_role }}"
  include: "slapd_monitoring.yml"
  tags:
    - monitoring

- name: "Services on {{ openldap_role }}"
  include: "services.yml"
  tags:
    - services
