---
# tasks file for roles/ae-dir-server

- name: "OS base configuration"
  include: "baseos_{{ ansible_os_family }}.yml"

- name: "Install OpenLDAP packages"
  include: "install_openldap_{{ ansible_os_family }}.yml"

- name: "TLS configuration for OpenLDAP slapd"
  include: tls_files.yml

- name: "Configure OpenLDAP slapd for AE-DIR"
  include: configure_slapd.yml

- name: "Configure OpenLDAP slapd for AE-DIR"
  include: system_accounts.yml

- name: "Specific tasks on OpenLDAP {{ openldap_role }}"
  include: "{{ openldap_role }}.yml"
