---
# tasks file for roles/ae-dir-server

- name: "OS base configuration"
  include: "baseos_{{ ansible_lsb.id }}.yml"

- name: "Install OpenLDAP packages"
  include: "install_openldap_{{ ansible_lsb.id }}.yml"

- name: "TLS configuration for OpenLDAP slapd"
  include: tls_files.yml
  tags:
    - openldap_tls_files

- name: "Configure OpenLDAP slapd for AE-DIR"
  include: configure_slapd.yml

- name: "Add system accounts on {{ openldap_role }}"
  include: system_accounts.yml
  when: openldap_role == 'provider'

- name: "Install various AE-DIR tools"
  include: aedir_tools.yml

- name: "Specific AE-DIR tool tasks on {{ ansible_lsb.id }}"
  include: "aedir_tools_{{ ansible_lsb.id }}.yml"

- name: "Specific AE-DIR tool tasks on {{ openldap_role }}"
  include: "aedir_tools_{{ openldap_role }}.yml"

- name: "Configure web2ldap for AE-DIR on {{ openldap_role }}"
  include: configure_web2ldap.yml
  when: openldap_role=="provider"

- name: "OATH-LDAP tasks on {{ openldap_role }}"
  include: "oath-ldap.yml"
  when: oath_ldap_enabled == "1"
