---
# tasks file for roles/ae-dir-server

- debug:
    var: "{{ item }}"
    verbosity: 1
  with_items:
    - inventory_dir
    - playbook_dir
    - role_path
    - aedir_templates_dirs
    - aedir_files_dirs

- name: "OS base configuration"
  include_tasks: "baseos_{{ lsb_id }}.yml"

- name: "Install AppArmor packages"
  include_tasks: "apparmor_{{ lsb_id }}.yml"
  when: apparmor_enabled == True
  tags:
    - apparmor

- name: "Install OpenLDAP packages"
  include_tasks: "install_openldap_{{ lsb_id }}.yml"

- name: "Install apache2 on {{ lsb_id }}"
  include_tasks: "install_apache2_{{ lsb_id }}.yml"
  when: openldap_role == 'provider'

- name: "Create directory structure {{ aedir_prefix }}"
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
  with_items:
    - "{{ aedir_etc }}"
    - "{{ aedir_etc }}/uwsgi"
    - "{{ aedir_bin }}"
    - "{{ aedir_sbin }}"
    - "{{ aedir_rundir }}"
    - "{{ aedir_rundir }}/uwsgi"
  tags:
    - aedir_tools

- name: "Add system accounts on {{ openldap_role }}"
  include_tasks: system_accounts.yml
  tags:
    - aedir_tools

- name: "Configure OpenLDAP slapd for AE-DIR"
  include_tasks: configure_slapd.yml
  tags:
     - slapd_conf

- name: "Install various AE-DIR tools"
  include_tasks: aedir_tools.yml
  tags:
    - aedir_tools

- name: "TLS configuration for OpenLDAP slapd"
  include_tasks: tls_files.yml
  tags:
    - openldap_tls_files

- name: "Specific AE-DIR tool tasks on {{ lsb_id }}"
  include_tasks: "aedir_tools_{{ lsb_id }}.yml"
  tags:
    - aedir_tools

- name: "Specific AE-DIR tool tasks on {{ openldap_role }}"
  include_tasks: "aedir_tools_{{ openldap_role }}.yml"
  tags:
    - aedir_tools

- name: "AE-DIR web pages {{ openldap_role }}"
  include_tasks: "aedir_htdocs.yml"
  when: openldap_role=="provider"
  tags:
    - htdocs

- name: "Configure apache2"
  include_tasks: "configure_apache2.yml"
  when: openldap_role == 'provider'
  tags:
     - apache_conf

- name: "Install AE-DIR password service (aedirpwd)"
  include_tasks: "aedirpwd.yml"
  when: openldap_role=="provider"
  tags:
    - aedirpwd

- name: "Install and configure web2ldap on {{ openldap_role }}"
  include_tasks: "web2ldap.yml"
  when: openldap_role=="provider"
  tags:
    - web2ldap

- name: "OATH-LDAP tasks on {{ openldap_role }}"
  include_tasks: "oath-ldap.yml"
  when: oath_ldap_enabled == True
  tags:
    - oath

- name: "OATH-LDAP enrollment web app on {{ openldap_role }}"
  include_tasks: "oathenroll.yml"
  when: oath_ldap_enabled == True and openldap_role=="provider"
  tags:
     - oath
     - oathenroll

- name: "Password sync tasks on {{ openldap_role }}"
  include_tasks: "pwsync.yml"
  when: openldap_role=="provider" and aedir_pwsync_targeturl
  tags:
     - pwsync

- name: "Monitoring scripts on {{ openldap_role }}"
  include_tasks: "slapd_monitoring.yml"
  tags:
    - monitoring

- name: "Services on {{ openldap_role }}"
  include_tasks: "services.yml"
  tags:
    - services
