---
# monitoring stuff

- name: "PIP install slapdcheck in virtualenv {{ aedir_prefix }}"
  pip:
    name:
      - slapdcheck>=3.10.0
    state: present
    virtualenv: "{{ aedir_prefix }}"
    extra_args: "{{ aedir_pip_extra_args }}"
  when: aedir_pip_install

- name: "Install slapdcheck package"
  zypper:
    name:
      - slapdcheck >= 3.10.0
    state: present
    disable_recommends: yes
    type: package
  when: lsb_id == 'SUSE'

- name: "Check status of directory {{ slapd_checkmk_local }}"
  stat:
    path: "{{ slapd_checkmk_local }}"
  register: slapd_checkmk_local_stat

- name: "Install slapdcheck configuration {{ aedir_etc }}/slapdcheck.cfg"
  template:
    src: "{{ slapdcheck_cfg_template }}"
    dest: "{{ aedir_etc }}/slapdcheck.cfg"
    owner: root
    group: root
    mode: 0o0644

- name: "Install check_mk local check {{ slapd_checkmk_local }}/slapd_checkmk.sh"
  template:
    src: "slapdcheck/slapd_checkmk.sh.j2"
    dest: "{{ slapd_checkmk_local }}/slapd_checkmk.sh"
    owner: root
    group: root
    mode: 0o0755
  when: slapd_checkmk_local != ""

- name: "Remove obsolete wrapper scripts"
  file:
    path: "{{ item }}"
    state: "absent"
  loop:
    - "{{ aedir_sbin }}/slapd_metrics.sh"
    - "{{ aedir_sbin }}/slapd_checkmk.sh"

- name: "Install slapdcheck wrapper script {{ aedir_sbin }}/slapdcheck.sh"
  template:
    src: "slapdcheck/slapdcheck.sh.j2"
    dest: "{{ aedir_sbin }}/slapdcheck.sh"
    owner: root
    group: root
    mode: 0o0755

- name: "Install systemd service unit {{ slapdcheck_service_name }}.service"
  ansible.builtin.template:
    src: "systemd/slapdcheck.service.j2"
    dest: "/etc/systemd/system/{{ slapdcheck_service_name }}.service"
    owner: "root"
    group: "root"
    mode: 0o0644

- name: "Install systemd timer unit {{ slapdcheck_service_name }}.timer"
  ansible.builtin.template:
    src: "systemd/slapdcheck.timer.j2"
    dest: "/etc/systemd/system/{{ slapdcheck_service_name }}.timer"
    owner: "root"
    group: "root"
    mode: 0o0644

- name: "Copy mtail programs to {{ mtail_progs }}/"
  template:
    src: "mtail/{{ item }}.mtail.j2"
    dest: "{{ mtail_progs }}/{{ item }}.mtail"
    follow: no
    owner: root
    group: root
    mode: 0o0644
  loop:
    - "{{ openldap_service_name }}"
    - aedir_proc
  when: mtail_progs is defined

- block:
  - name: "Create directory for metrics text exports {{ aedir_metricsdir }}"
    file:
      path: "{{ aedir_metricsdir }}"
      state: directory
      owner: root
      group: "{{ aedir_metrics_owner_group }}"
      mode: 0o0750
  - name: "Generate static metrics file {{ aedir_metricsdir }}/ae-dir-conf.prom"
    template:
      src: "ae-dir-conf.prom.j2"
      dest: "{{ aedir_metricsdir }}/ae-dir-conf.prom"
      owner: root
      group: "{{ aedir_metrics_owner_group }}"
      mode: 0o0640
  when: aedir_metricsdir != ""
