---
# Install OATH-LDAP enrollment web service (oathenroll)

- name: "PIP install OATH-LDAP web apps in virtualenv {{ aedir_prefix }}"
  pip:
    name:
      - oath-ldap-web
    state: latest
    virtualenv: "{{ aedir_prefix }}"
    extra_args: "{{ aedir_pip_extra_args }}"
  when: aedir_pip_install
  notify:
    - "restart oathenroll"

- name: "Install OATH-LDAP web apps package"
  zypper:
    name:
      - oath-ldap-web
    state: "{{ aedir_zypper_state }}"
    disable_recommends: yes
    type: package
  when: lsb_id == 'SUSE'
  notify:
    - "restart oathenroll"

- name: "Create directories for oathenroll"
  file:
    path: "{{ oath_ldap_cfg_dir }}/{{ item }}"
    state: directory
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
  loop:
    - "oathenroll"
    - "oathenroll/templates"

- name: "Copy oathenroll HTML templates to {{ oath_ldap_cfg_dir }}/oathenroll/templates"
  copy:
    src: "oath-ldap/oathenroll/templates/"
    dest: "{{ oath_ldap_cfg_dir }}/oathenroll/templates"
    follow: no
    owner: root
    group: root
    mode: u=rw,g=r,o=r
    directory_mode: u=rwx,g=rx,o=rx
  notify:
    - "restart oathenroll"

- name: "Create {{ oath_ldap_cfg_dir }}/oathenroll/oathenroll.cfg"
  template:
    src: "{{ item }}"
    dest: "{{ oath_ldap_cfg_dir }}/oathenroll/oathenroll.cfg"
    owner: root
    group: "{{ oath_ldap_oathenroll_web_group }}"
    mode: 0o0640
  with_first_found:
    - files:
        - "oath-ldap/oathenroll.cfg.j2"
      paths: "{{ aedir_templates_dirs }}"
  notify:
    - "restart oathenroll"

- name: "Create socket directory {{ aedir_rundir }}/oathenroll"
  file:
    path: "{{ aedir_rundir }}/oathenroll"
    state: directory
    owner: ae-dir-otpenroll
    group: ae-dir-httpd
    mode: u=rwx,g=rx,o=
  when: aedir_service_manager != "systemd" or not aedir_rundir.startswith("/run")
  notify:
    - "restart oathenroll"

- name: "Install systemd unit {{ aedir_systemd_dir }}/oathenroll.service"
  template:
    src: "systemd/oathenroll.service.j2"
    dest: "{{ aedir_systemd_dir }}/oathenroll.service"
    owner: root
    group: root
    mode: 0o0644
  notify:
    - "restart oathenroll"
  when: aedir_service_manager == "systemd"

- name: "Create AppArmor profile for oathenroll"
  template:
    src: "apparmor/gunicorn-app.j2"
    dest: "{{ apparmor_profiles_dir }}/oathenroll"
    owner: root
    group: root
    mode: 0o0644
  vars:
    name: oathenroll
    cfgdir: "{{ oath_ldap_cfg_dir }}/oathenroll"
  notify:
    - "restart apparmor"
    - "restart oathenroll"
  when: apparmor_enabled == True
