---
# OATH-LDAP tasks

- name: "Add local system group {{ oath_listener_user }} for external bind listener"
  group:
    name: "{{ oath_listener_user }}"
    gid: "{{ aedir_ldapi_services[oath_listener_user].gid_number }}"
    state: present
    system: yes

- name: "Add local system account {{ oath_listener_user }} for external bind listener"
  user:
    name: "{{ oath_listener_user }}"
    comment: "{{ aedir_ldapi_services[oath_listener_user].description }}"
    uid: "{{ aedir_ldapi_services[oath_listener_user].uid_number }}"
    group: "{{ aedir_ldapi_services[oath_listener_user].gid_number }}"
    shell: "/bin/true"
    state: present
    system: yes
    createhome: no

- name: "Create master key directory {{ aedir_etc }}/oath-master-keys"
  file:
    path: "{{ aedir_etc }}/oath-master-keys"
    state: directory
    owner: root
    group: "{{ oath_listener_user }}"
    mode: u=rwx,g=rxs,o=
  when: openldap_role=="provider"
  notify:
    - "restart {{ oath_bind_listener }}"

- name: "Create socket directory {{ oath_ldap_socket_dir }}"
  file:
    path: "{{ oath_ldap_socket_dir }}"
    state: directory
    owner: "{{ oath_listener_user }}"
    group: root
    mode: u=rwx,g=rx,o=rx

- name: "Install {{ oath_bind_listener }}.py"
  copy:
    src: "oath-ldap/{{ oath_bind_listener }}.py"
    dest: "{{ aedir_sbin }}/{{ oath_bind_listener }}.py"
    owner: root
    group: "{{ oath_listener_user }}"
    mode: 0750
  notify:
    - "restart {{ oath_bind_listener }}"

- name: "Install systemd unit file for {{ oath_bind_listener }}"
  template:
    src: "oath-ldap/{{ oath_bind_listener }}.service.j2"
    dest: "{{ aedir_systemd_dir }}/{{ oath_bind_listener }}.service"
    owner: root
    group: root
    mode: 0644
  notify:
    - reload systemd
    - "restart {{ oath_bind_listener }}"
  when: ansible_service_mgr=="systemd"

- name: "Enable and start service {{ oath_bind_listener }}"
  service:
    name: "{{ oath_bind_listener }}"
    state: started
    enabled: yes

- name: "OATH-LDAP enrollment web app on {{ openldap_role }}"
  include: "oathenroll.yml"
  when: openldap_role=="provider"
