---
# Install AE-DIR password service (oathenroll)

- name: "Create directories for oathenroll"
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
  with_items:
    - "{{ aedir_etc }}/oathenroll"
    - "{{ aedir_etc }}/oathenroll/templates"

- name: "copy oathenroll HTML templates to {{ aedir_etc }}/oathenroll/templates"
  copy:
    src: "oath-ldap/oathenroll/templates/"
    dest: "{{ aedir_etc }}/oathenroll/templates"
    follow: no
    owner: root
    group: root
    mode: u=rw,g=r,o=r
    directory_mode: u=rwx,g=rx,o=rx
  notify:
    - "restart oathenroll"

- name: "Create oathenroll_cnf.py"
  template:
    src: "{{ item }}"
    dest: "{{ aedir_etc }}/oathenroll/oathenroll_cnf.py"
    owner: root
    group: "{{ oath_ldap_oathenroll_web_group }}"
    mode: 0640
  with_first_found:
    - files:
       - "oath-ldap/oathenroll_cnf.py.j2"
      paths: "{{ aedir_templates_dirs }}"
  notify:
    - "restart oathenroll"

- name: "Install OATH enrollment web application"
  copy:
    src: "oath-ldap/oathenroll/oathenroll.py"
    dest: "{{ aedir_python_sitepackages }}/oathenroll.py"
    owner: root
    group: "{{ oath_ldap_oathenroll_web_group }}"
    mode: 0750
  notify:
    - "restart oathenroll"

- name: "Create UWSGI socket directory for oathenroll"
  file:
    path: "{{ aedir_rundir }}/uwsgi/oathenroll"
    state: directory
    owner: ae-dir-otpenroll
    group: ae-dir-httpd
    mode: u=rwx,g=rx,o=
  notify:
    - "restart oathenroll"

- name: "Create uwsgi.ini for oathenroll"
  template:
    src: "uwsgi.ini.j2"
    dest: "{{ aedir_etc }}/uwsgi/{{ name }}.ini"
    owner: root
    group: root
    mode: 0644
  vars:
    name: oathenroll
    user: ae-dir-pwd
    module: "oathenroll:application"
    master: "true"
    processes: "{{ aedir_uwsgi_params.oathenroll.processes }}"
    threads: 0
    stats_port: 9093
    buffer_size: "{{ aedir_uwsgi_params.oathenroll.buffer_size }}"
    harakiri: "{{ aedir_uwsgi_params.oathenroll.harakiri }}"
  notify:
    - "restart oathenroll"

- name: Install systemd unit file from template
  template:
    src: "oath-ldap/oathenroll.service.j2"
    dest: "{{ aedir_systemd_dir }}/oathenroll.service"
    owner: root
    group: root
    mode: 0644
  notify:
    - "restart oathenroll"
  when: aedir_service_manager == "systemd"

- name: "Create AppArmor profile for oathenroll"
  template:
    src: "apparmor/uwsgi-python.j2"
    dest: "{{ apparmor_profiles_dir }}/oathenroll"
    owner: root
    group: root
    mode: 0644
  vars:
    name: oathenroll
  notify:
    - "restart apparmor"
    - "restart oathenroll"
  when: apparmor_enabled == True
