---
# tasks for password sync

- name: "Add local system group {{ aedir_pwsync_listener_user }} for external PASSMOD listener"
  group:
    name: "{{ aedir_pwsync_listener_user }}"
    gid: "{{ aedir_ldapi_services[aedir_pwsync_listener_user].gid_number }}"
    state: present
    system: yes

- name: "Add local system account {{ aedir_pwsync_listener_user }} for external PASSMOD listener"
  user:
    name: "{{ aedir_pwsync_listener_user }}"
    comment: "{{ aedir_ldapi_services[aedir_pwsync_listener_user].description }}"
    uid: "{{ aedir_ldapi_services[aedir_pwsync_listener_user].uid_number }}"
    group: "{{ aedir_ldapi_services[aedir_pwsync_listener_user].gid_number }}"
    shell: "/bin/true"
    state: present
    system: yes
    createhome: no

- name: "Create socket directory {{ aedir_pwsync_socket_dir }}"
  file:
    path: "{{ aedir_pwsync_socket_dir }}"
    state: directory
    owner: "{{ aedir_pwsync_listener_user }}"
    group: root
    mode: u=rwx,g=rx,o=rx

- name: "Install passmod.py"
  copy:
    src: "passmod.py"
    dest: "{{ aedir_sbin }}/passmod.py"
    owner: root
    group: "{{ aedir_pwsync_listener_user }}"
    mode: 0750
  notify:
    - "restart passmod"

- name: "Install systemd unit file for PASSMOD listener"
  template:
    src: "passmod.service.j2"
    dest: "{{ aedir_systemd_dir }}/passmod.service"
    owner: root
    group: root
    mode: 0644
  notify:
    - reload systemd
    - "restart passmod"
  when: ansible_service_mgr=="systemd"

