---
# tasks for password sync

- name: "Add local system group {{ aedir_pwsync_listener_user }} for external PASSMOD listener"
  group:
    name: "{{ aedir_pwsync_listener_user }}"
    gid: "{{ aedir_ldapi_services[aedir_pwsync_listener_user].gid_number }}"
    state: present
    system: yes
  notify:
    - "restart pwsync"

- name: "Add local system account {{ aedir_pwsync_listener_user }} for external PASSMOD listener"
  user:
    name: "{{ aedir_pwsync_listener_user }}"
    comment: "{{ aedir_ldapi_services[aedir_pwsync_listener_user].description }}"
    uid: "{{ aedir_ldapi_services[aedir_pwsync_listener_user].uid_number }}"
    group: "{{ aedir_ldapi_services[aedir_pwsync_listener_user].gid_number }}"
    shell: "{{ aedir_nologin_shell }}"
    state: present
    system: yes
    createhome: no
  notify:
    - "restart pwsync"

- name: "Create config directory {{ aedir_pwsync_targetpwfile|dirname }}"
  file:
    path: "{{ aedir_pwsync_targetpwfile|dirname }}"
    state: directory
    owner: root
    group: "{{ aedir_pwsync_listener_user }}"
    mode: u=rwx,g=rx,o=
  notify:
    - "restart pwsync"

- name: "Install CA cert for target connection to {{ aedir_pwsync_cacert_pathname }}"
  copy:
    src: "{{ aedir_pwsync_cacert_filename }}"
    dest: "{{ aedir_pwsync_cacert_pathname }}"
    follow: no
    owner: root
    group: root
    mode: u=rw,g=r,o=r
    directory_mode: u=rwx,g=rx,o=rx
  notify:
    - "restart pwsync"

- name: "Create password file {{ aedir_pwsync_targetpwfile }}"
  copy:
    content: "{{ aedir_pwsync_targetpassword }}"
    dest: "{{ aedir_pwsync_targetpwfile }}"
    owner: root
    group: "{{ aedir_pwsync_listener_user }}"
    mode: u=rwx,g=rx,o=
  notify:
    - "restart pwsync"
  when: aedir_pwsync_targetpassword != ""
  no_log: True

- name: "Create socket directory {{ aedir_pwsync_socket_dir }}"
  file:
    path: "{{ aedir_pwsync_socket_dir }}"
    state: directory
    owner: "{{ aedir_pwsync_listener_user }}"
    group: root
    mode: u=rwx,g=rx,o=rx
  notify:
    - "restart pwsync"

- name: "Install systemd unit file for PASSMOD listener"
  template:
    src: "systemd/pwsync.service.j2"
    dest: "{{ aedir_systemd_dir }}/pwsync.service"
    owner: root
    group: root
    mode: 0o0644
  notify:
    - "restart pwsync"
  when: aedir_service_manager == "systemd"
