---

# enable running services

- name: "Enable slapd is running"
  service:
    name: slapd
    state: started
    enabled: yes

- name: "Ensure {{ cron_service_name }} is running"
  service:
    name: "{{ cron_service_name }}"
    state: started
    enabled: yes
  when: openldap_role=="provider"

- name: "Ensure {{ web_server }} is running"
  service:
    name: "{{ web_server }}"
    state: started
    enabled: yes
  when: openldap_role=="provider"

- name: "ensure polkit is running"
  service:
    name: "polkit"
    state: started
    enabled: yes
  when: openldap_role=="provider" and lsb_id == "CentOS"

- name: "Ensure aedirpwd is running"
  service:
    name: "aedirpwd"
    state: started
    enabled: yes
  when: openldap_role=="provider"

- name: "Enable and start service {{ oath_bind_listener }}"
  service:
    name: "{{ oath_bind_listener }}"
    state: started
    enabled: yes
  when: oath_ldap_enabled == True

- name: "ensure oathenroll is running"
  service:
    name: "oathenroll"
    state: started
    enabled: yes
  when: openldap_role=="provider" and oath_ldap_enabled == True

- name: "Ensure PASSMOD listener service is running"
  service:
    name: "passmod"
    state: started
    enabled: yes
  when: openldap_role=="provider" and aedir_pwsync_enabled == True
