---
# monitoring stuff

- name: "Remove {{ aedir_sbin }}/slapd_checkmk.py"
  file:
    path: "{{ aedir_sbin }}/slapd_checkmk.py"
    state: absent

- name: "PIP install slapdcheck in virtualenv {{ aedir_prefix }}"
  pip:
    name:
      - slapdcheck>=3.6.1
    state: present
    virtualenv: "{{ aedir_prefix }}"
    extra_args: "{{ aedir_pip_extra_args }}"
  when: aedir_pip_install

- name: "Install slapdcheck package on {{ openldap_role }}"
  zypper:
    name:
      - slapdcheck >= 3.6.1
    state: present
    disable_recommends: yes
    type: package
  when: lsb_id == 'SUSE'

- name: "Check status of directory {{ slapd_checkmk_local }}"
  stat:
    path: "{{ slapd_checkmk_local }}"
  register: slapd_checkmk_local_stat

- name: "Install check_mk local check {{ slapd_checkmk_local }}/slapd_checkmk.sh"
  template:
    src: "slapd_checkmk.sh.j2"
    dest: "{{ slapd_checkmk_local }}/slapd_checkmk.sh"
    owner: root
    group: root
    mode: 0755

- name: "Install metrics wrapper script {{ slapd_metrics_local }}/slapd_metrics.sh"
  template:
    src: "slapd_metrics.sh.j2"
    dest: "{{ aedir_sbin }}/slapd_metrics.sh"
    owner: root
    group: root
    mode: 0755
