---
# Add system accounts

- name: "Add local system account groups for services running accessing AE-DIR providers via LDAPI"
  group:
    name: "{{ item.key }}"
    gid: "{{ item.value.gid_number }}"
    state: present
    system: yes
  with_dict:
    "{{ aedir_ldapi_services }}"
  when: openldap_role == 'provider'

- name: "Add local system accounts for services running accessing AE-DIR providers via LDAPI"
  user:
    name: "{{ item.key }}"
    comment: "{{ item.value.description }}"
    uid: "{{ item.value.uid_number }}"
    group: "{{ item.value.gid_number }}"
    shell: "/bin/true"
    state: present
    system: yes
    createhome: no
  with_items:
    "{{ aedir_ldapi_services }}"
  when: openldap_role == 'provider'

