---
# tasks file for roles/web2ldap

- name: "Unpack {{ web2ldap_filename }} to {{ web2ldap_prefix }}"
  unarchive:
    src: "{{ web2ldap_src }}"
    dest: "/opt"
    copy: yes
    creates: "{{ web2ldap_prefix }}"
    mode: a+r
    owner: root
    group: root
  notify:
    - "restart {{ web_server }}"

- name: "Install fcgi.py"
  copy:
    src: "web2ldap/fcgi.py"
    dest: "{{ web2ldap_pylib }}/fcgi.py"
  notify:
    - restart web2ldap

- name: "Compile {{ web2ldap_prefix }}"
  shell: "{{ aedir_python }} -O -m compileall {{ web2ldap_prefix }}"
  args:
    creates: "{{ web2ldap_pylib }}/w2lapp/__init__.pyo"

- name: Remove .htaccess file
  file:
    dest: "{{ web2ldap_htdocs }}/.htaccess"
    state: absent
