---
# handlers file for roles/ae-dir

- name: reload systemd
  sudo: yes
  command: systemctl daemon-reload

- name: restart slapd
  service: name=slapd state=restarted

- name: restart aedirpwd
  service: name=aedirpwd state=restarted
