---
# handlers file for roles/ae-dir

- name: reload systemd
  command: systemctl daemon-reload

- name: restart slapd
  service: name=slapd state=restarted

- name: restart aedirpwd
  service: name=aedirpwd state=restarted
  when: openldap_role == 'provider'

- name: restart hotp_validator
  service: name=hotp_validator state=restarted
  when: openldap_role == 'provider' and oath_ldap_enabled == '1'

- name: restart oathenroll
  service: name=oathenroll state=restarted
  when: openldap_role == 'provider' and oath_ldap_enabled == '1'

- name: restart bind_proxy
  service: name=bind_proxy state=restarted
  when: openldap_role == 'consumer' and oath_ldap_enabled == '1'
